README.md, docs/arguments.md, docs/grpc.md, docs/http.md, docs/intro.md, docs/linting.md, docs/module-hooks.md, docs/releasing.md, docs/service-activity.md, docs/testing.md, manifest.yaml
**What this PR does**: Adds documentation for stencil-golang and the service it generates
=> docs: add docs

manifest.yaml, templates/_helpers.tpl, templates/devenv.yaml.tpl
* adds a devenv.yaml file to track various things a devenv may need to
deploy a service. right now we're only tracking dependencies.
* this allows other stencil modules to programmatically add depedencies
via module hooks.
[XX-XX]
=> feat: devenv.yaml

templates/api/clients/node/package.hjson.tpl
[RMS-718]
[RMS-718]: https://outreach-io.atlassian.net/browse/RMS-718?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: run yarn install before build

manifest.yaml, templates/_helpers.tpl, templates/deployments/appname/app.jsonnet.tpl
Allows toggling OpenTelemetry for tracing.
[DTSS-1825]
The otel functionality is mainly controlled by library versions. We nee to make sure we are ready to switch before bumping the default library versions.
[DTSS-1825]: https://outreach-io.atlassian.net/browse/DTSS-1825?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: add support for otel tracing

templates/devenv.yaml.tpl
This PR adds the `service` field to the `devenv.yaml`
[XX-XX]
=> feat(devenv): add service

templates/deployments/appname/app.jsonnet.tpl
=> feat: add node port service

templates/deployments/appname/app.jsonnet.tpl
Removes the nodeport service from being created automatically.
[XX-XX]
=> revert: remove nodeport service

templates/monitoring/datadog.tf.tpl
=> fix: remove bentos arg

templates/deployments/docker.yaml.tpl
See https://github.com/getoutreach/devbase/pull/269
[XX-XX]
=> feat(docker): generate docker.yaml for devbase builder

templates/monitoring/dashboard.tf.tpl, templates/monitoring/datadog.tf.tpl, templates/monitoring/main.tf.tpl, templates/monitoring/terraform.tfvars.tpl, templates/monitoring/versions.tf.tpl
Title says, it does. I don't think we meant to generate these for non-service repositories.
[XX-XX]
=> fix(monitoring): generate only if a service

templates/monitoring/datadog.tf.tpl
=> fix: use bento name in datadog terraform

manifest.yaml
This cleans up the `manifest.yaml` and allows it to be processed by other applications now that it is the schema format
[DT-2524]
[DT-2524]: https://outreach-io.atlassian.net/browse/DT-2524?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: Rewrite manifest.yaml in full schema format

templates/devspace.yaml.tpl
Adds e2e profile so we can run e2e tests inside devspacefd
[DTSS-1601]
[DTSS-1601]: https://outreach-io.atlassian.net/browse/DTSS-1601?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: add e2e profile to devspace

manifest.yaml
=> fix: correct type in manifest

templates/deployments/appname/app.jsonnet.tpl
Ensures we correctly add scrape annotations when using the `dual` metrics flag.
[XX-XX]
=> fix: support dual scrape annotations

templates/monitoring/dashboard.tf.tpl
=> fix: add otel blocks for dual dashboards

templates/.prettierignore.tpl
=> fix: markdown formatting

manifest.yaml, templates/monitoring/datadog.tf.tpl
Supports the changes in https://github.com/getoutreach/bootstrap/pull/1357
[DT-2543]
[DT-2543]: https://outreach-io.atlassian.net/browse/DT-2543?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: deployTo -> deployment (DT-2543)

templates/monitoring/dashboard.tf.tpl
The original move to otel had a bad copy paste in it. This corrects that issue and applies the right template.
Bulkworkflow was updated as as a test:
https://app.datadoghq.com/dashboard/dmn-wpd-znf/terraform-bulkworkflow?tpl_var_env=staging&from_ts=1659534828163&to_ts=1659621228163&live=true
[XX-XX]
=> fix: use correct dashboard sections

scripts/.tool-versions
=> fix: releasing

.releaserc.yaml, go.mod, go.sum, service.yaml, stencil.lock
=> feat: enable rc branch release flow

templates/internal/appName/rpctest/suite.go.tpl
=> fix: remove legacy reference to .underscoreTitleAppName

.releaserc.yaml, .tool-versions, bootstrap.lock, go.mod, go.sum, manifest.yaml, stencil.lock, templates/_helpers.tpl
This PR moves us to use `go 1.19` by default, and allows the go version to be (partially, if with bootstrap) overriden via the `versions.go` key.
[XX-XX]
=> feat(golang): 1.19

manifest.yaml, templates/deployments/appname/app.jsonnet.tpl
Adds lightstep as an additional endpiont so that we we can run a POC.
[DT-2637]
[DT-2637]: https://outreach-io.atlassian.net/browse/DT-2637?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> featch: support lightstep as an additional enpoint

.circleci/config.yml, stencil.lock, templates/_helpers.tpl
This re-stencils the module to fully support rc branch release flow and updates libraries.
[XX-XX]
=> fix: re-stencil and update library versions

.circleci/config.yml, .releaserc.yaml, go.mod, go.sum, stencil.lock
=> fix: re-stencil

templates/deployments/appname/mixins/devenv.jsonnet.tpl, templates/deployments/appname/mixins/kubernetes.jsonnet.tpl
Prevents double file extensions on mixins.
Removes a double file exteni
[DT-2787]
[DT-2787]: https://outreach-io.atlassian.net/browse/DT-2787?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: remove double file extension from devenv.jsonnet

manifest.yaml
Ensures that we default to OpenTelemetry for all new repos or newly upgraded repos.
[DT-2508]
[DT-2508]: https://outreach-io.atlassian.net/browse/DT-2508?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: default tracing to OpenTelemetry

manifest.yaml, templates/monitoring/datadog.tf.tpl
support multiple service domains
https://outreach-io.atlassian.net/browse/DT-2593
=> fix: support multiple service domains

templates/.snapshots/TestRenderDeploymentOverride-deployments-appname-app.override.jsonnet.tpl-deployments-testing-testing.override.jsonnet.snapshot, templates/deployments/appname/app.override.jsonnet.tpl
=> fix(deployments): remove leftover isLocalDev reference

.releaserc.yaml, README.md, bootstrap.lock, docs/module-hooks.md, go.mod, go.sum, package.json, service.yaml, stencil.lock, templates/.snapshots/TestRenderDeploymentOverride-deployments-appname-app.override.jsonnet.tpl-deployments-testing-testing.override.jsonnet.snapshot, templates/deployments/appname/app.override.jsonnet.tpl, templates/deployments/appname/mixins/devenv.jsonnet.tpl, templates/deployments/appname/mixins/kubernetes.jsonnet.tpl, templates/deployments/appname/resources.libsonnet.tpl, templates/internal/appName/rpc/rpc.go.tpl, yarn.lock
This PR contains a few fixes to issues found when running this on `rms`.
[DT-2808]
=> fix: small fixes

templates/cmd/main.go.tpl
Slight issue discovered when running on a CLI only repository
[DT-2808]
=> fix(cmd/main): skip if not a service

templates/api/rpc/client.go.tpl, templates/devspace.yaml.tpl
Promote unstable to rc, created by `dt release promote`
=> Promote unstable to rc

templates/_helpers.tpl
We need to ensure that teams update to the latest version so that the generate `orgservice` code works as expected.
[XX-XX]
=> fix: bump orgservice

templates/.snapshots/TestBasicGoMod-go.mod.tpl-go.mod.snapshot, templates/.snapshots/TestMergeGoMod-go.mod.tpl-go.mod.snapshot, templates/_helpers.tpl
This PR bumps `gobox` to v1.54.0 to get support for go install/run, and fix issues with invalid semver handling in CLIs.
[DT-2808]
=> fix(deps): gobox 1.54.0

docs/grpc.md
I noticed the docs link was broken, so I fixed it.
None
=> feat(docs): fix broken groups link

templates/internal/appName/rpc/rpc.go.tpl
=> fix: missing struct

templates/.snapshots/TestDevenvYaml-devenv.yaml.tpl-devenv.yaml.snapshot, templates/.snapshots/TestEmptyDevenvYaml-devenv.yaml.tpl-devenv.yaml.snapshot, templates/devenv.yaml.tpl, templates/main_test.go
Does as the title says, I guess we just never did this post-move :smile:
[DT-2808]
=> fix(devenv): store dependencies from arguments

templates/.snapshots/TestRenderDeploymentJsonnet-deployments-appname-app.jsonnet.tpl-deployments-testing-testing.jsonnet.snapshot, templates/deployments/appname/app.jsonnet.tpl
Add MY_REGION to support https://github.com/getoutreach/gobox/pull/233
https://outreach-io.atlassian.net/browse/DT-2373
=> fix: add MY_REGION env var

templates/_helpers.tpl
Deleting these files can cause issues when repos have decided to add custom version of them. This PR skips generating them, but avoids deleting.
[XX-XX]
=> fix: avoid deleting files when configs change

templates/.snapshots/TestRenderDependabot-.github-dependabot.yml.tpl-.github-dependabot.yml.snapshot, templates/_helpers.tpl, templates/api/clients/node/package.hjson.tpl
Hotfixes commit "8e1f8b525daded4c309ff87520352e281a9e68d4" into channel stable, created by `dt release hotfix`
=> chore: Hotfix 8e1f8b525daded4c309ff87520352e281a9e68d4 into channel stable

manifest.yaml, templates/deployments/docker.yaml.tpl
=> feat(githubAction): add github actions to docker.yaml.tpl

manifest.yaml, templates/.snapshots/TestRenderDeploymentDockerfile-deployments-appname-Dockerfile.tpl-deployments-testing-Dockerfile.snapshot
This PR upgrades Go to 1.19.2 to fix some CVEs.
[XX-XX]
Depends on https://github.com/getoutreach/outreach-docker/pull/481
=> fix(go): 1.19.2

templates/cmd/main.go.tpl
If the service shuts down because of an error it should exit with a code.
[XX-XX]
=> feat: on an error exit with a code

manifest.yaml
Remove dependency from `stencil-actions` 
DT-2925
=> fix: remove dependency from stencil-actions

templates/.snapshots/TestRenderDeploymentJsonnet-deployments-appname-app.jsonnet.tpl-deployments-testing-testing.jsonnet.snapshot, templates/deployments/appname/app.jsonnet.tpl, templates/main_test.go
* hopefully this fixes the issue of randomly sorting this list on every stencil run?
[XX-XX]
=> fix: sort mixins

templates/.snapshots/TestDatadogTf-monitoring-datadog.tf.tpl-monitoring-datadog.tf.snapshot, templates/main_test.go, templates/monitoring/datadog.tf.tpl
https://outreach-io.atlassian.net/browse/DT-3141
=> fix: Update datadog application monitors to use individual pod limit

.circleci/config.yml, .tool-versions, .vscode/launch.json, scripts/golangci.yml, service.yaml, stencil.lock
Switches to stable version of all module and re-stencils. Test of full release.
[XX-XX]
=> fix: re-stencil 11-29-2022

templates/internal/appName/kafka/consumer.go.tpl
We need to write a custom block here in Grappler. You can find more details on the ticket.
[DT-3207]
[DT-3207]: https://outreach-io.atlassian.net/browse/DT-3207?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: Add StencilBlock in KafkaConsumerService Run

docs/arguments.md, manifest.yaml, templates/monitoring/datadog.tf.tpl
[DT-3225]
[DT-3225]: https://outreach-io.atlassian.net/browse/DT-3225?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(monitoring): change http_latency_high threshold to configurable (DT-3225)

.gitignore, go.mod, go.sum, service.yaml, stencil.lock, templates/.snapshots/TestDevenvYaml-devenv.yaml.tpl-devenv.yaml.snapshot
restencil for [testing RC changes](https://outreach-io.atlassian.net/wiki/spaces/DT/pages/2388198102/SOP+Releasing+Dev+Tooling+Updates#Testing-RC-changes)
[XX-XX]
=> fix: restencil for testing RC changes

templates/internal/appName/kafka/consumer.go.tpl
Adding stencil block for imports to support another stencil blocks content.
[ORES-1803]
[ORES-1803]: https://outreach-io.atlassian.net/browse/ORES-1803?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: [ORES-1803] Adding new stencil block

templates/internal/appName/kafka/consumer.go.tpl
Hotfixes commit(s) "fdbca25e137d20c7f7a61b1bec6d05e0b00c0d3d" into channel rc, created by `dt release hotfix`
=> chore: Hotfix fdbca25e137d20c7f7a61b1bec6d05e0b00c0d3d into channel rc

templates/internal/appName/http/httpservice.go.tpl
* various bugs with dep injenction
[XX-XX]
=> fix: dep injection

templates/internal/appName/http/httpservice.go.tpl
Hotfixes commit(s) "4df210b9ef6307f692ae0f522089f2c63d4ec72c" into channel stable, created by `dt release hotfix`
=> chore: Hotfix 4df210b9ef6307f692ae0f522089f2c63d4ec72c into channel stable

templates/cmd/main.go.tpl
The comment on the dependencies struct is misspelled, causing linters to fail after re-stencil.
[XX-XX]
=> fix: depedencies -> dependencies

templates/cmd/main.go.tpl
Hotfixes commit(s) "6a5ee6a43380d4026dc530e4e6216198025e153f" into channel stable, created by `dt release hotfix`
=> chore: Hotfix 6a5ee6a43380d4026dc530e4e6216198025e153f into channel stable

.circleci/config.yml, go.mod, go.sum, service.yaml, stencil.lock
Skips e2e test since we don't have any, and skips docker since it will no longer work with the newest devbase.
[XX-XX]
=> fix: skip docker and e2e steps in CI

.circleci/config.yml, monitoring/slos.tf, service.yaml, stencil.lock
Removes dependency on `stencil-discovery`.
[DT-3385]
[DT-3385]: https://outreach-io.atlassian.net/browse/DT-3385?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: remove private modules

CONTRIBUTING.md, service.yaml, stencil.lock
Uses rc versions that do not depend on stencil-discovery.
[DT-3385](https://outreach-io.atlassian.net/browse/DT-3385?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ)
[DT-3385]: https://outreach-io.atlassian.net/browse/DT-3385?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: dependencies without discovery

CONTRIBUTING.md, service.yaml, stencil.lock
Promote unstable to rc, created by `dt release promote`
=> chore: Promote unstable to rc

templates/_helpers.tpl
Updates the node gRPC version to be newer to handle some incompatibilities apparently.
=> fix(deps): update node grpc version

manifest.yaml, templates/.snapshots/TestGoModStanzaVersion-go.mod.tpl-go.mod.snapshot, templates/go.mod.tpl, templates/main_test.go
Adds an argument to update the go.mod go stanza version.
[DT-3442]
[DT-3442]: https://outreach-io.atlassian.net/browse/DT-3442?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: go stanza version

manifest.yaml, templates/.snapshots/TestRenderDeploymentDockerfile-deployments-appname-Dockerfile.tpl-deployments-testing-Dockerfile.snapshot, templates/_helpers.tpl
On the tin. Go 1.19.2 -> 1.19.5 tools version
[DT-3446]
[DT-3446]: https://outreach-io.atlassian.net/browse/DT-3446?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: update go tools-version to 1.19.5

manifest.yaml, templates/.snapshots/TestBasicGoMod-go.mod.tpl-go.mod.snapshot, templates/.snapshots/TestMergeGoMod-go.mod.tpl-go.mod.snapshot
=> feat: default go mod to golang 1.19

manifest.yaml, templates/.snapshots/TestRenderDeploymentJsonnet-deployments-appname-app.jsonnet.tpl-deployments-testing-testing.jsonnet.snapshot, templates/deployments/appname/app.jsonnet.tpl
Setting tracing.opentelemetry should send to the open telemetry collector configured for tracing.
[DT-3472]
[DT-3472]: https://outreach-io.atlassian.net/browse/DT-3472?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: enable ability to send traces to the otel collector

manifest.yaml, templates/.snapshots/TestRenderDeploymentJsonnet-deployments-appname-app.jsonnet.tpl-deployments-testing-testing.jsonnet.snapshot, templates/.snapshots/TestRenderDeploymentJsonnet_Canary-deployments-appname-app.jsonnet.tpl-deployments-testing-testing.jsonnet.snapshot, templates/.snapshots/TestRenderDeploymentJsonnet_Canary_emptyServiceActivities-deployments-appname-app.jsonnet.tpl-deployments-testing-testing.jsonnet.snapshot, templates/deployments/appname/app.jsonnet.tpl, templates/main_test.go
- add deployment strategy to manifest
- support canary deployment
- add default metrics for canary deployment (http and grpc)
https://outreach-io.atlassian.net/browse/DT-2918
=> feat: support canary deployment

templates/api/clients/node/.tool-versions.tpl
We need to skip the file at the top of it, to prevent whitespace issues.
[XX-XX]
=> fix(grpcClients): move node skip to top of file

templates/monitoring/slos.tf.tpl
I tried to restencil flubby which is a library with the latest code and it generated the slo monitoring template.
https://github.com/getoutreach/flubby/pull/113
https://outreach-io.atlassian.net/browse/STAR-1036
=> fix: skip slo defintion if not a service

templates/internal/appName/k8s/activity.go.tpl
=> fix: Whitespace in activity.go.tpl

templates/.snapshots/TestSkipSLOsTf-monitoring-slos.tf.tpl-monitoring-slos.tf.snapshot, templates/main_test.go, templates/monitoring/slos.tf.tpl
Basically on the tin:
Adds a skip SLO test and if SLOs are skipped we shouldn't render the module hook SLOs either.
[DT-3524]
[DT-3524]: https://outreach-io.atlassian.net/browse/DT-3524?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: add skip slo test and skip generating module hook sl os

templates/.snapshots/TestRenderDeploymentJsonnet-deployments-appname-app.jsonnet.tpl-deployments-testing-testing.jsonnet.snapshot, templates/.snapshots/TestRenderDeploymentJsonnet_Canary-deployments-appname-app.jsonnet.tpl-deployments-testing-testing.jsonnet.snapshot, templates/.snapshots/TestRenderDeploymentJsonnet_Canary_emptyServiceActivities-deployments-appname-app.jsonnet.tpl-deployments-testing-testing.jsonnet.snapshot, templates/deployments/appname/app.jsonnet.tpl
Removes: "add ability to remove deployment replicas when using hpa (#184)""
=> fix: removes the prune added in 696623f5

docs/module-hooks.md, templates/cmd/main.go.tpl
We already have a stencil block for the services to add more dependency. Need a way to add more dependency for stencil modules
https://outreach-io.atlassian.net/browse/STAR-1200
=> feat: added ModuleHook for dependencyInjection

templates/.snapshots/TestBasicGoMod-go.mod.tpl-go.mod.snapshot, templates/.snapshots/TestGoModStanzaVersion-go.mod.tpl-go.mod.snapshot, templates/.snapshots/TestMergeGoMod-go.mod.tpl-go.mod.snapshot, templates/_helpers.tpl
=> feat: Bumping gobox from 1.54.0 to 1.64.0

.circleci/config.yml, opslevel.yml, service.yaml, stencil.lock
=> fix: add release notification

pkg/go.mod, templates/.snapshots/TestBasicGoMod-go.mod.tpl-go.mod.snapshot, templates/.snapshots/TestGoModStanzaVersion-go.mod.tpl-go.mod.snapshot, templates/.snapshots/TestMergeGoMod-go.mod.tpl-go.mod.snapshot, templates/_helpers.tpl
=> feat: Pulling in latest gobox (v1.68.0)

templates/.snapshots/TestDatadogTf-monitoring-datadog.tf.tpl-monitoring-datadog.tf.snapshot, templates/.snapshots/TestDatadogTf_Override-monitoring-datadog.tf.tpl-monitoring-datadog.tf.snapshot, templates/monitoring/datadog.tf.tpl
update argocd metrics based on the changes from [argocd upgrade using helmchart](https://github.com/getoutreach/argocd/commit/580b7746d3025dc6e738aa7e20a778c9d348a931) 
argocd container name has changed from argocd_application_controller to application_controller
**tested** https://app.datadoghq.com/metric/explorer?start=1680208521879&end=1680212121879&paused=false#N4Ig7glgJg5gpgFxALlAGwIYE8D2BXJVEADxQEYAaELcqyKBAC1pEbghkcLIF8qo4AMwgA7CAgg4RKUAiwAHOChASAtnADOcAE4RNIKtrgBHPJoQaUAbVBGN8qVoD6gnNtUZCKiOq279VKY6epbINiAiGOrKQdpYZAYgUJ4YThr42gDGSsgg6gi6mZaBZnHKqqLIGPLyaBCZnpIiTplSBThoaDoAdBjaMDiZUE7V8k6irsCR6sgCtThYCOZ+AG71cBRsGGhMaQieeBrIWzuMWBSZaIdL2k7TcMga+zCiMGQYPAAEAEZYn8CXa46O5ROA8EB8UD3GKlLAAJkSyX2aQy2XKiEKxRAsRouQqIiqNTqDQkUhabW0HS62l6-UGw1G4xEk3uszg80Wyx0a2yFA0WBEmT2ByO-MFcCgFyuT2BrKeGBe …
=> fix(monitoring): update argocd metrics

templates/.snapshots/TestDatadogTf-monitoring-datadog.tf.tpl-monitoring-datadog.tf.snapshot, templates/.snapshots/TestDatadogTf_Override-monitoring-datadog.tf.tpl-monitoring-datadog.tf.snapshot, templates/monitoring/datadog.tf.tpl
Hotfixes commit(s) "d333bd42aa090b78db08dce6165f9400a4b179b5" into channel stable, created by `dt release hotfix`
=> chore: Hotfix d333bd42aa090b78db08dce6165f9400a4b179b5 into channel stable

manifest.yaml, templates/.snapshots/TestRenderDeploymentDockerfile-deployments-appname-Dockerfile.tpl-deployments-testing-Dockerfile.snapshot
**What this PR does**: Sets the default `terraform` version to `1.4.4`
=> feat: terraform 1.4.4

manifest.yaml, templates/.snapshots/TestRenderDeploymentDockerfile-deployments-appname-Dockerfile.tpl-deployments-testing-Dockerfile.snapshot
This PR upgrades Go to `1.20.2`
[XX-XX]
=> feat: golang 1.20.2

templates/api/clients/node/src/client-helpers.ts.tpl
Removing `accessToken` and auth interceptor as this forces clients to create client for each request. Instead authentication will be handled directly in Giraffe, via shared interceptor.
[ORES-1910]
[ORES-1910]: https://outreach-io.atlassian.net/browse/ORES-1910?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: [ORES-1910] Remove access token and auth interceptor

manifest.yaml, templates/.snapshots/TestRenderDeploymentDockerfile-deployments-appname-Dockerfile.tpl-deployments-testing-Dockerfile.snapshot
Upgrades `golang` to `1.20.3` as the default.
[XX-XX]
=> feat(golang): 1.20.3

templates/devspace.yaml.tpl
Hotfixes commit(s) "42bb0373c0f25165244ee6c81d31f5edd536499a" into channel stable, created by `dt release hotfix`
=> chore: Hotfix 42bb0373c0f25165244ee6c81d31f5edd536499a into channel stable

templates/api/clients/node/src/client-helpers.ts.tpl
Hotfixes commit(s) "5176ff87ce72167511a7198f70275d77cabafefa" into channel stable, created by `dt release hotfix`
=> chore: Hotfix 5176ff87ce72167511a7198f70275d77cabafefa into channel stable

templates/.snapshots/TestDevspaceYaml-devspace.yaml.tpl-devspace.yaml.snapshot, templates/main_test.go
Hotfixes commit(s) "8f17f6a0f5611efded0c35d0cb801a39d069682d" into channel stable, created by `dt release hotfix`
=> chore: Hotfix 8f17f6a0f5611efded0c35d0cb801a39d069682d into channel stable

templates/.snapshots/TestVSCodeLaunchConfig-.vscode-launch.json.tpl-.vscode-launch.json.snapshot, templates/main_test.go
Hotfixes commit(s) "e0b5837b892c3046b25ee96a3532300f3fb5d7bc" into channel stable, created by `dt release hotfix`
=> chore: Hotfix e0b5837b892c3046b25ee96a3532300f3fb5d7bc into channel stable

templates/deployments/appname/app.config.jsonnet.tpl
=> fix: add comma for jsonnet formatting

templates/deployments/appname/app.config.jsonnet.tpl
Hotfixes commit(s) "f2f18f0b1f9732b3e2df4ffaf11a1bf8c11c2045, 906b514454065d8b7769c4db3b007d212920ac69" into channel stable, created by `dt release hotfix`
=> chore: Hotfix f2f18f0b1f9732b3e2df4ffaf11a1bf8c11c2045 into channel stable

templates/.snapshots/TestBasicGoMod-go.mod.tpl-go.mod.snapshot, templates/.snapshots/TestGoModStanzaVersion-go.mod.tpl-go.mod.snapshot, templates/.snapshots/TestMergeGoMod-go.mod.tpl-go.mod.snapshot, templates/_helpers.tpl
This PR upgrades `gobox` and `services` to handle a regression in the `trace` library.
[DT-3752]
[DT-3752]: https://outreach-io.atlassian.net/browse/DT-3752?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(deps): upgrade gobox and services

templates/.snapshots/TestDevspaceYaml-devspace.yaml.tpl-devspace.yaml.snapshot, templates/devspace.yaml.tpl
This allows teams to run `devenv app e2e -t` to iteratively test applications.
[DT-3753]
[DT-3753]: https://outreach-io.atlassian.net/browse/DT-3753?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(devspace): add e2e with terminal profile

.circleci/config.yml, .github/dependabot.yml, .vscode/launch.json, go.mod, go.sum, opslevel.yml, package.json, scripts/golangci.yml, stencil.lock, yarn.lock
=> feat(stencil): restencil

templates/.snapshots/TestRenderDeploymentJsonnet-deployments-appname-app.jsonnet.tpl-deployments-testing-testing.jsonnet.snapshot, templates/.snapshots/TestRenderDeploymentJsonnetWithHPA-deployments-appname-app.jsonnet.tpl-deployments-testing-testing.jsonnet.snapshot, templates/.snapshots/TestRenderDeploymentJsonnet_Canary-deployments-appname-app.jsonnet.tpl-deployments-testing-testing.jsonnet.snapshot, templates/.snapshots/TestRenderDeploymentJsonnet_Canary_emptyServiceActivities-deployments-appname-app.jsonnet.tpl-deployments-testing-testing.jsonnet.snapshot, templates/deployments/appname/app.jsonnet.tpl
Adds a nonDevelopmentObjects block to clean this up a little bit.
Inside of that block there are two conditional objects: HPA and ArgoRollouts configuration.
[XX-XX]
=> refactor(app jsonnet): add non-dev objects block

templates/.snapshots/TestRenderDeploymentJsonnet-deployments-appname-app.jsonnet.tpl-deployments-testing-testing.jsonnet.snapshot, templates/.snapshots/TestRenderDeploymentJsonnetWithHPA-deployments-appname-app.jsonnet.tpl-deployments-testing-testing.jsonnet.snapshot, templates/.snapshots/TestRenderDeploymentJsonnet_Canary-deployments-appname-app.jsonnet.tpl-deployments-testing-testing.jsonnet.snapshot, templates/.snapshots/TestRenderDeploymentJsonnet_Canary_emptyServiceActivities-deployments-appname-app.jsonnet.tpl-deployments-testing-testing.jsonnet.snapshot, templates/deployments/appname/app.jsonnet.tpl
Since we're renaming the otel-collector this needs to be updated to match.
[XX-XX]
=> feat: change tracing collector endpoint

templates/.snapshots/TestDatadogTf-monitoring-datadog.tf.tpl-monitoring-datadog.tf.snapshot, templates/.snapshots/TestDatadogTf_Override-monitoring-datadog.tf.tpl-monitoring-datadog.tf.snapshot, templates/monitoring/datadog.tf.tpl
Hotfixes commit(s) "73c9ff1eef918f19222f1035c3739228a69507c1" into channel stable, created by `dt release hotfix`
=> chore: Hotfix 73c9ff1eef918f19222f1035c3739228a69507c1 into channel stable

manifest.yaml, templates/.snapshots/TestRenderDeploymentDockerfile-deployments-appname-Dockerfile.tpl-deployments-testing-Dockerfile.snapshot, templates/.snapshots/TestVSCodeLaunchConfig-.vscode-launch.json.tpl-.vscode-launch.json.snapshot
Hotfixes commit(s) "6b8baa3948a5fac60eb14fafc2118b16a87a5547" into channel stable, created by `dt release hotfix`
=> chore: Hotfix 6b8baa3948a5fac60eb14fafc2118b16a87a5547 into channel stable

manifest.yaml, templates/.snapshots/TestRenderDeploymentDockerfile-deployments-appname-Dockerfile.tpl-deployments-testing-Dockerfile.snapshot, templates/.snapshots/TestVSCodeLaunchConfig-.vscode-launch.json.tpl-.vscode-launch.json.snapshot
Approval PR for a manual merge
=> Merge "rc" into "main"

templates/.snapshots/TestDevspaceYaml-devspace.yaml.tpl-devspace.yaml.snapshot, templates/devspace.yaml.tpl
Change skip port forwarding to also skip the dlv port
[DT-3900]
[DT-3900]: https://outreach-io.atlassian.net/browse/DT-3900?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> revert: Change skip port forwarding to also skip the dlv port

.circleci/config.yml, stencil.lock
Run stencil to remove Opslevel check
[XX-XX]
=> fix: run stencil

templates/.snapshots/TestDevspaceYaml-devspace.yaml.tpl-devspace.yaml.snapshot, templates/deployments/appname/mixins/devenv.jsonnet.tpl, templates/devspace.yaml.tpl
Hotfixes commit(s) "ec614ae6593f3a15ecc244a5c2d5e57ceddfde18" into channel rc, created by `dt release hotfix`
=> chore: Hotfix ec614ae6593f3a15ecc244a5c2d5e57ceddfde18 into channel rc

templates/.snapshots/TestDevspaceYaml-devspace.yaml.tpl-devspace.yaml.snapshot, templates/devspace.yaml.tpl
This should fix problems some people were having with OOM kills in various places by default.
[DT-3950]
Ignore the whitespace changes, those were autogenerated by VSCode.
[DT-3950]: https://outreach-io.atlassian.net/browse/DT-3950?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(devspace): explicitly set requests/limits on devspace container

manifest.yaml
Hotfixes commit(s) "12f9fbcf968413220fb6eea0ea2aa4d7cfaa5d92" into channel stable, created by `dt release hotfix`
=> chore: Hotfix 12f9fbcf968413220fb6eea0ea2aa4d7cfaa5d92 into channel stable

templates/.snapshots/TestDevspaceYaml-devspace.yaml.tpl-devspace.yaml.snapshot, templates/devspace.yaml.tpl, templates/main_test.go
Fixes a regression introduced in #358.
Also fixes a typo in the tests.
[DT-3950]
This will need to be hotfixed into RC, as this was found when updating to the RC.
[DT-3950]: https://outreach-io.atlassian.net/browse/DT-3950?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(devspace): put requests/limits in the correct config

templates/.snapshots/TestDevspaceYaml-devspace.yaml.tpl-devspace.yaml.snapshot, templates/devspace.yaml.tpl, templates/main_test.go
Hotfixes commit(s) "345be2bd8791e2194f5829d2545ca8fe50decd3a" into channel rc, created by `dt release hotfix`
=> chore: Hotfix 345be2bd8791e2194f5829d2545ca8fe50decd3a into channel rc

manifest.yaml
=> Merge "release" into "rc"

manifest.yaml
=> feat: Upgrade nodejs version

templates/_helpers.tpl
* upgrades these dependencies to fix a security vulnerability
[INFOSEC-16771]
[INFOSEC-16771]: https://outreach-io.atlassian.net/browse/INFOSEC-16771?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: upgrade services and httpx

templates/api/clients/node/.eslintrc.js.tpl, templates/api/clients/node/README.md.tpl, templates/api/clients/node/jest.config.js.tpl, templates/api/clients/node/scripts/copy-definitions.js.tpl, templates/api/clients/node/src/client-helpers.ts.tpl, templates/api/clients/node/tsconfig.json.tpl
Promote rc to stable, created by `dt release promote`
=> chore: Promote rc to stable

manifest.yaml, templates/.snapshots/TestDontIncludeRubyToolVersionsIfNotRubyGRPCCLient-testdata-tool-versions-ruby-.tool-versions.tpl-testdata-tool-versions-ruby-.tool-versions.snapshot, templates/.snapshots/TestIncludeRubyToolVersionsIfRubyGRPCCLient-testdata-tool-versions-ruby-.tool-versions.tpl-testdata-tool-versions-ruby-.tool-versions.snapshot, templates/.snapshots/TestRenderDeploymentDockerfile-deployments-appname-Dockerfile.tpl-deployments-testing-Dockerfile.snapshot, templates/.snapshots/TestVSCodeLaunchConfig-.vscode-launch.json.tpl-.vscode-launch.json.snapshot
Does what it says on the tin.
[DT-4094]
[DT-4094]: https://outreach-io.atlassian.net/browse/DT-4094?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: upgrade go to 1.21.3

templates/_helpers.tpl
Companion PR to https://github.com/getoutreach/devbase/pull/684
=> fix: upgrade prettier to ^3.0.0

manifest.yaml
Hotfixes commit(s) "2ded2125b072bec9dffdfae07cc17e956b5f6450" into channel rc, created by `dt release hotfix`
=> chore: Hotfix 2ded2125b072bec9dffdfae07cc17e956b5f6450 into channel rc

manifest.yaml, templates/.snapshots/TestRenderAPIGoSuccess-api-api.go.tpl-api-testing.go.snapshot, templates/.snapshots/TestRenderDeploymentConfig-deployments-appname-app.config.jsonnet.tpl-deployments-testing-testing.config.jsonnet.snapshot, templates/.snapshots/TestRenderDeploymentJsonnet-deployments-appname-app.jsonnet.tpl-deployments-testing-testing.jsonnet.snapshot, templates/.snapshots/TestRenderDeploymentJsonnetWithHPA-deployments-appname-app.jsonnet.tpl-deployments-testing-testing.jsonnet.snapshot, templates/.snapshots/TestRenderDeploymentJsonnet_Canary-deployments-appname-app.jsonnet.tpl-deployments-testing-testing.jsonnet.snapshot, templates/.snapshots/TestRenderDeploymentJsonnet_Canary_emptyServiceActivities-deployments-appname-app.jsonnet.tpl-deployments-testing-testing.jsonnet.snapshot, templates/.snapshots/TestRenderDeploymentOverride-deployments-appname-app.override.jsonnet.tpl-deployments-testing-testing.override.jsonnet.snapshot, templates/deployments/appname/app.jsonnet.tpl
This adds an ability to opt-in to topology aware routing to reduce cross AZ costs.
[XX-XX]
=> feat: add optional topology aware routing and scheduling constraints

manifest.yaml, templates/.goreleaser.yml.tpl, templates/.snapshots/TestGoreleaserYml-.goreleaser.yml.tpl-.goreleaser.yml.snapshot, templates/main_test.go
Add block for additional env variables in goreleaser.
[DT-4161]
[DT-4161]: https://outreach-io.atlassian.net/browse/DT-4161?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: support custom environment variables for arbitrary CLIs

templates/.snapshots/TestRenderDeploymentJsonnet-deployments-appname-app.jsonnet.tpl-deployments-testing-testing.jsonnet.snapshot, templates/.snapshots/TestRenderDeploymentJsonnetWithHPA-deployments-appname-app.jsonnet.tpl-deployments-testing-testing.jsonnet.snapshot, templates/.snapshots/TestRenderDeploymentJsonnet_Canary-deployments-appname-app.jsonnet.tpl-deployments-testing-testing.jsonnet.snapshot, templates/.snapshots/TestRenderDeploymentJsonnet_Canary_emptyServiceActivities-deployments-appname-app.jsonnet.tpl-deployments-testing-testing.jsonnet.snapshot, templates/deployments/appname/app.jsonnet.tpl
https://outreach-io.atlassian.net/browse/DT-4154
=> fix(deployments): ensure service account is always created

.circleci/config.yml, .tool-versions, .vscode/launch.json, scripts/devbase.sh, service.yaml, stencil.lock
- update devbase to RC, to update lintroller.
[XX-XX]
=> fix(deps): update lintroller

templates/.snapshots/TestRenderDeploymentJsonnet-deployments-appname-app.jsonnet.tpl-deployments-testing-testing.jsonnet.snapshot, templates/.snapshots/TestRenderDeploymentJsonnetWithHPA-deployments-appname-app.jsonnet.tpl-deployments-testing-testing.jsonnet.snapshot, templates/.snapshots/TestRenderDeploymentJsonnet_Canary-deployments-appname-app.jsonnet.tpl-deployments-testing-testing.jsonnet.snapshot, templates/.snapshots/TestRenderDeploymentJsonnet_Canary_emptyServiceActivities-deployments-appname-app.jsonnet.tpl-deployments-testing-testing.jsonnet.snapshot, templates/.snapshots/TestUseKIAMFalse-deployments-appname-app.jsonnet.tpl-deployments-testing-testing.jsonnet.snapshot, templates/deployments/appname/app.jsonnet.tpl
Change the maxUnavailable to 10% to reduce extra cost when draining nodes.
Feature request: https://outreach-hq.slack.com/archives/C01CAR6GVPD/p1710492579539699 
[XX-XX]
=> feat: change the PDB maxUnavailable to 10%

templates/.snapshots/TestRenderDeploymentJsonnet-deployments-appname-app.jsonnet.tpl-deployments-testing-testing.jsonnet.snapshot, templates/.snapshots/TestRenderDeploymentJsonnetWithHPA-deployments-appname-app.jsonnet.tpl-deployments-testing-testing.jsonnet.snapshot, templates/.snapshots/TestRenderDeploymentJsonnet_Canary-deployments-appname-app.jsonnet.tpl-deployments-testing-testing.jsonnet.snapshot, templates/.snapshots/TestRenderDeploymentJsonnet_Canary_emptyServiceActivities-deployments-appname-app.jsonnet.tpl-deployments-testing-testing.jsonnet.snapshot, templates/.snapshots/TestUseKIAMFalse-deployments-appname-app.jsonnet.tpl-deployments-testing-testing.jsonnet.snapshot, templates/deployments/appname/app.jsonnet.tpl
=> fix: PDB maxUnavailable value needs to be a string

templates/_helpers.tpl
* wait-on, grpc/grpc-js, getoutreach/grpc-client, winston
=> fix: upgrade node packages for vulns

templates/_helpers.tpl
Hotfixes commit(s) "e5e724c979f16983b803b756cb02fb89012bf4a8" into channel stable, created by `dt release hotfix`
=> chore: Hotfix e5e724c979f16983b803b756cb02fb89012bf4a8 into channel stable

templates/_helpers.tpl
Hotfixes commit(s) "a554f9878db99128c33a167a32af88ca9b785488" into channel stable, created by `dt release hotfix`
=> chore: Hotfix a554f9878db99128c33a167a32af88ca9b785488 into channel stable

stencil.lock
Run stencil to update the devbase version.
[XX-XX]
=> fix: update devbase version

service.yaml
Update the prerelease branch to let the script run on main branch.
Also remove the opslevel namespace.
[XX-XX]
=> fix: update prerelease branch

templates/api/clients/ruby/client.gemspec.tpl
I'm developing ruby library for audit and I'd need to extend gemspec file with my own directives. This is a proposal to add own updates to `gemspec` file.
[ADS-334]
[ADS-334]: https://outreach-io.atlassian.net/browse/ADS-334?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: add possibility of own directives to gemspec

templates/api/clients/ruby/lib/client.rb.tpl
I'd need to add some custom code to ruby code and I'm proposing to add stencil block to be able to add some code there.
[ADS-334]
[ADS-334]: https://outreach-io.atlassian.net/browse/ADS-334?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: add possibility of own ruby code in client

cortex.yaml
Does what it says on the tin.
Limited auto-updating will be handled in a future PR, when a new `devbase` RC is released.
=> chore: add Cortex manifest

.circleci/config.yml, service.yaml, stencil.lock
=> fix(stencil): enable weekly RC releases

.circleci/config.yml, .releaserc.yaml, service.yaml, stencil.lock
https://outreach-io.atlassian.net/browse/DT-4349
=> fix: update automated RC release

.releaserc.yaml, package.json, service.yaml, stencil.lock, yarn.lock
- add `force: true` in service.yaml to build binaries on release
[XX-XX]
=> fix(release): build binaries on release

docs/module-hooks.md, templates/.snapshots/TestRenderDeploymentConfig-deployments-appname-app.config.jsonnet.tpl-deployments-testing-testing.config.jsonnet.snapshot, templates/_helpers.tpl, templates/deployments/appname/app.config.jsonnet.tpl, templates/deployments/appname/app.jsonnet.tpl
* adds the ability to inject vault secrets via a module hook
=> feat: inject secrets via module hook

templates/.snapshots/TestRenderDeploymentJsonnet-deployments-appname-app.jsonnet.tpl-deployments-testing-testing.jsonnet.snapshot, templates/.snapshots/TestRenderDeploymentJsonnetWithHPA-deployments-appname-app.jsonnet.tpl-deployments-testing-testing.jsonnet.snapshot, templates/.snapshots/TestRenderDeploymentJsonnet_Canary-deployments-appname-app.jsonnet.tpl-deployments-testing-testing.jsonnet.snapshot, templates/.snapshots/TestRenderDeploymentJsonnet_Canary_emptyServiceActivities-deployments-appname-app.jsonnet.tpl-deployments-testing-testing.jsonnet.snapshot, templates/.snapshots/TestUseKIAMFalse-deployments-appname-app.jsonnet.tpl-deployments-testing-testing.jsonnet.snapshot, templates/deployments/appname/app.jsonnet.tpl
Making PDBs slightly less restrictive which will allow faster cluster consolidations. This will not affect a lot of services, only those with highest amount of replicas.
[XX-XX]
=> feat(deployments): change PDB default to 15%

manifest.yaml, templates/.snapshots/TestRenderDeploymentJsonnet-deployments-appname-app.jsonnet.tpl-deployments-testing-testing.jsonnet.snapshot, templates/.snapshots/TestRenderDeploymentJsonnetWithHPA-deployments-appname-app.jsonnet.tpl-deployments-testing-testing.jsonnet.snapshot, templates/.snapshots/TestRenderDeploymentJsonnet_Canary-deployments-appname-app.jsonnet.tpl-deployments-testing-testing.jsonnet.snapshot, templates/.snapshots/TestRenderDeploymentJsonnet_Canary_emptyServiceActivities-deployments-appname-app.jsonnet.tpl-deployments-testing-testing.jsonnet.snapshot, templates/.snapshots/TestUseKIAMFalse-deployments-appname-app.jsonnet.tpl-deployments-testing-testing.jsonnet.snapshot, templates/deployments/appname/app.jsonnet.tpl, templates/main_test.go
- Remove Kiam's code
- Do not touched args `useKIAM` -> because it's still using by some apps
[XX-XX]
=> feat: remove KIAM functionality

templates/.snapshots/TestDevspaceYaml-devspace.yaml.tpl-devspace.yaml.snapshot, templates/.snapshots/TestRenderDeploymentDockerfile-deployments-appname-Dockerfile.tpl-deployments-testing-Dockerfile.snapshot, templates/main_test.go
Avoid hardcoding real registry values in test snapshots.
[DT-4466]
[DT-4466]: https://outreach-io.atlassian.net/browse/DT-4466?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> test: use fixture for docker pull registry

templates/.snapshots/TestRenderDeploymentJsonnet-deployments-appname-app.jsonnet.tpl-deployments-testing-testing.jsonnet.snapshot, templates/.snapshots/TestRenderDeploymentJsonnetWithHPA-deployments-appname-app.jsonnet.tpl-deployments-testing-testing.jsonnet.snapshot, templates/.snapshots/TestRenderDeploymentJsonnet_Canary-deployments-appname-app.jsonnet.tpl-deployments-testing-testing.jsonnet.snapshot, templates/.snapshots/TestRenderDeploymentJsonnet_Canary_emptyServiceActivities-deployments-appname-app.jsonnet.tpl-deployments-testing-testing.jsonnet.snapshot, templates/deployments/appname/app.jsonnet.tpl
[COR-6706](https://outreach-io.atlassian.net/browse/COR-6706)
Added a new version label to pods. This is a recommendation from istio for better Observability. 
[COR-6706]: https://outreach-io.atlassian.net/browse/COR-6706?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: Add version label deployment

templates/.github/dependabot.yml.tpl, templates/.snapshots/TestRenderDependabot-.github-dependabot.yml.tpl-.github-dependabot.yml.snapshot
=> fix(dependabot): fix stencil block syntax
