templates/internal/appName/doc.go.tpl

fixes linter error from doculint on hyphens

fix: adds doculint nolint for doc.go

---

manifest.yaml
templates/deployments/appname/app.jsonnet.tpl

Adds support for toggling between `datadog` and `opentelemetry` as the metrics collector.
[DTSS-1818]
[DTSS-1818]: https://outreach-io.atlassian.net/browse/DTSS-1818?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: allow toggling metrics collector

---

templates/cmd/main_cli.go.tpl

This PR removes unused import from main_cli.go template.
Running bootstrap on the smartstore repo (lib only) fails with: 
```
ruby 2.6.6 is already installed
terraform 0.13.5 is already installed
INFO[0021]  - go mod tidy                               
INFO[0023]  - Format Files                              
:: Running gogenerate
../../cmd/smartstore/smartstore.go:13:2: imported and not used: "github.com/getoutreach/gobox/pkg/exec"
internal/pgtest/generate.go:7: running "go": exit status 2
make: *** [gogenerate] Error 1
ERRO[0036] failed to run: run codegen: failed to run post run command for module "github.com/getoutreach/stencil-base": exit status 2 
ERRO[0045] failed to run: failed to run stencil: exit status 1 
```
[DTSS-00]

fix: remove unused import from main_cli causing bootstrap v10 to fail

---

templates/.vscode/extensions.json.tpl
templates/.vscode/settings.json.tpl

Adds the [popular prettier extension to VSCode](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) so that Markdown files get autoformatted on save.
[DTSS-2081]
Please note that this does not resolve DTSS-2081, but rather works around it if DTSS decides to temporarily remove Markdown formatting support from Stencil while they don't have bandwidth to work on the bug I reported.
[DTSS-2081]: https://outreach-io.atlassian.net/browse/DTSS-2081?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(vscode): default formatter for markdown to prettier

---

templates/_helpers.tpl

[DTSS-1849](https://outreach-io.atlassian.net/browse/DTSS-1849) - eslint is breaking on some authz code because it is using a fairly old eslint parser version. This upgrades the version which should unblock authz from bootstrapping.

fix: issue with older version of eslint parser

---

.circleci/config.yml
bootstrap.lock
templates/_helpers.tpl

This change restores the behavior of the basing the appImportPath on the `box` configuration. The behavior was changed in https://github.com/getoutreach/stencil-golang/pull/34/files This restores the original behavior.
[DT-2170]
[DT-2170]: https://outreach-io.atlassian.net/browse/DT-2170?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: return use of dynamic org from box config

---

manifest.yaml
templates/monitoring/dashboard.tf.tpl
templates/monitoring/datadog.tf.tpl
templates/monitoring/main.tf.tpl
templates/monitoring/terraform.tfvars.tpl
templates/monitoring/versions.tf.tpl

Migrates the monitoring terraform templates from bootstrap. This is needed before we add OpenTelemetry support to the automatically generated alerts and dashboards.
[DTSS-1911]
[DTSS-1911]: https://outreach-io.atlassian.net/browse/DTSS-1911?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add monitoring terraform templates

---

manifest.yaml
templates/deployments/docker.yaml.tpl

Title says, it does. This PR technically breaks `customDockerfile`, but I don't think there's really a good path-forward for that argument anyways. Instead, the user should create `deployments/docker.yaml` as needed for their custom dockerfiles.
When this is going to go out we should probably do that [for users of `customDockerfile`](https://cs.github.com/?scopeName=All+repos&scope=&q=org%3Agetoutreach+%22customDockerfile%3A+true%22).
[XX-XX]
PRs:
* https://github.com/getoutreach/flubby/pull/90
* https://github.com/getoutreach/smartstore/pull/130

fix(docker): generate docker.yaml only if a service

---

manifest.yaml
templates/monitoring/dashboard.tf.tpl
templates/monitoring/datadog.tf.tpl

Adds support for `datadog`, `opentelemetry`, or `dual` metrics and monitoring.
- Only uses the datadog scraper
- Spins up a single dashboard for datadog metrics
- Uses datadog style metrics for monitoring
- Only uses the otel scraper
- Spins up a single dashboard for otel metrics
- Uses otel style metrics for monitoring
- Uses both otel and datadog scraper
- Spins up two dashboard, one for datadog and one for otel
- Uses datadog style metrics for monitoring
[DT-1833]
[DT-1910]
[DT-1833]: https://outreach-io.atlassian.net/browse/DT-1833?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DT-1910]: https://outreach-io.atlassian.net/browse/DT-1910?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: support otel for monitoring

---

templates/monitoring/datadog.tf.tpl

* everything else uses limits and using requests only makes sense
if requests == limits
[XX-XX]

fix: use cpu limits not requests for monitor

---

templates/.snapshots/TestRenderDeploymentConfig-deployments-appname-app.config.jsonnet.tpl-deployments-testing-app.config.jsonnet.snapshot
templates/deployments/appname/app.config.jsonnet.tpl

- jsonnetfmt doesn't like to be missing this semicolon
```
-> jsonnetfmt (.jsonnet/.libsonnet)
./deployments/smartstorecdctestconsumer/app.config.jsonnet:78:1-6 Expected , or ; but got "local"
make: *** [fmt] Error 1
ERRO[0253] failed to run: run codegen: failed to run post run command for module "github.com/getoutreach/stencil-base": exit status 2
ERRO[0259] failed to run: failed to run stencil: exit status 1
```
[XX-XX]

fix(jsonnet): missing semicolon

---

templates/.github/dependabot.yml.tpl
templates/.snapshots/TestRenderDependabot-.github-dependabot.yml.tpl-.github-dependabot.yml.snapshot

apparently YAML doesn't allow tabs ????
```
[error] .github/dependabot.yml: SyntaxError: Plain value cannot start with a tab character (5:1)
[error]   3 | updates:
[error]   4 | 	# Golang dependencies
[error] > 5 | 	- package-ecosystem: "gomod"
[error]     | ^^^^^^^^^^^^^^^^^^^^
[error]   6 | 		directory: "/"
[error]   7 | 		schedule:
[error]   8 | 			interval: "daily"
make: *** [fmt] Error 1
ERRO[0086] failed to run: run codegen: failed to run post run command for module "github.com/getoutreach/stencil-base": exit status 2
ERRO[0112] failed to run: failed to run stencil: exit status 1
```
- changes tabs to spaces in dependabot.yml
[QSS-1316]
[QSS-1316]: https://outreach-io.atlassian.net/browse/QSS-1316?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU …

fix(dependabot): change tabs to spaces

---

templates/monitoring/datadog.tf.tpl

This PR cleans up a leftover `serviceDomain` reference when we moved to `serviceDomains`.
[XX-XX]

fix(monitoring): cleanup leftover serviceDomain reference

---

templates/_helpers.tpl

We have recently moved to protoc 3.21.5 (released under tag = 21.5). However, stencil-golang keeps reverting it back. Putting a patch here to ensure it sticks.
[CDT-00]

fix: upgrade protoc to 21.5, aka 3.21.5

---

templates/.snapshots/TestRenderDeploymentDockerfile-deployments-appname-Dockerfile.tpl-deployments-testing-Dockerfile.snapshot
templates/deployments/appname/Dockerfile.tpl
templates/main_test.go

Since we moved to `mage` in devbase, we now have an issue where `make dep` can fail with `mage` not being installed. Instead of hacking in mage, for now we switch to `go mod download`. We need to redesign this dockerfile to unify the tooling between CI, local, and docker images to go back to calling `make` in the dockerfile
[DT-2825]
[DT-2825]: https://outreach-io.atlassian.net/browse/DT-2825?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(dockerfile): use go mod download over make dep

---

templates/_helpers.tpl
templates/internal/appName/rpc/rpc.go.tpl

This PR adds support for passing gRPC options to `StartServer`
[DT-2606]
[DT-2606]: https://outreach-io.atlassian.net/browse/DT-2606?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(rpc): allow to pass server options

---

templates/_helpers.tpl
templates/api/clients/ruby/.tool-versions.tpl
templates/api/clients/ruby/client.gemspec.tpl

context: https://outreach-hq.slack.com/archives/CN9MU7GLW/p1663335947482609?thread_ts=1663330514.908369&cid=CN9MU7GLW

feat: get rid of Ruby 2.6 references

---

templates/devspace.yaml.tpl

This PR exposes `BOX_REPOSITORY_URL` to the devspace container, which is used by `box.sh` for downloading box. This helps implement https://github.com/getoutreach/devbase/pull/309
[DT-2843]
[DT-2843]: https://outreach-io.atlassian.net/browse/DT-2843?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(devspace): pass box URL

---

templates/api/rpc/client.go.tpl

This PR fixes `client.go` to properly generate the first time
[DT-2808]

fix(grpc/client): remove duplicate import, pass clientOpts to grpcx

---

templates/devspace.yaml.tpl

When running tests and linters inside a devenv container, they complain about the project not being a git repository. This includes the necessary git directory. This shouldn't increase the image size too much and will allow all commands to run successfully inside the devspace pod.
[XX-XX]

fix: include .git directory in devbase sync

---

.circleci/config.yml
.editorconfig
.goreleaser.yml
.releaserc.yaml
bootstrap.lock
go.sum
internal/plugin/merge.go
internal/plugin/plugin.go
manifest.yaml
plugin/main.go
service.yaml
stencil.lock
templates/.snapshots/TestBasicGoMod-go.mod.tpl-go.mod.snapshot
templates/.snapshots/TestMergeGoMod-go.mod.tpl-go.mod.snapshot
templates/.snapshots/TestRenderDependabot-.github-dependabot.yml.tpl-.github-dependabot.yml.snapshot
templates/.snapshots/testdata/go.mod
templates/_helpers.tpl
templates/go.mod.tpl
templates/main_test.go

This PR migrates the original bootstrap `go.mod` processor to stencil, in a stencil native way (a extension!). This PR contains the new go module "processor" (extension) and the `go.mod` template code needed to use it.
This `go.mod` function merges the on disk `go.mod` with a generated one from dependencies from module hooks, and baked in dependencies. This is done by adding a extension with `MergeGoMod` that merges the right hand `go.mod` into the left hand one, keeping dependencies if they are higher than the right hand `go.mod`
[DT-2093]
[DT-2093]: https://outreach-io.atlassian.net/browse/DT-2093?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: generate/merge go.mod

---

manifest.yaml
templates/deployments/appname/app.jsonnet.tpl

We are ready to fully remove honeycomb as a specified tracing provider. This will allow us to finally bump up the version of `services`, `httpx`, and `gobox`.
[XX-XX]

fix: remove honeycomb tracing

---

templates/.vscode/settings.json.tpl

This PR adds support for running lintroller+golangci-lint in VSCode
[DT-1612]
Depends on https://github.com/getoutreach/devbase/pull/317
[DT-1612]: https://outreach-io.atlassian.net/browse/DT-1612?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(vscode): lintroller

---

templates/scripts/golangci.yml.tpl

Repeating consts in tests is a normal pattern and the linter should not complain about this, so this change excludes it. See this thread: https://outreach-hq.slack.com/archives/CM3TW594L/p1664580535961139
[DT-2947](https://outreach-io.atlassian.net/browse/DT-2947)
[DT-2947]: https://outreach-io.atlassian.net/browse/DT-2947?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: exclude goconst linter in tests

---

templates/scripts/golangci.yml.tpl

These linters are deprecated in favor of the "unused" linter, which is already enabled.

fix: Remove deprecated linters.

---

templates/scripts/golangci.yml.tpl

Removes config lines that only applied to our fork of golangci-lint we stopped using.
[XX-XX]

fix(golangci-lint): remove older severity rules that applied to fork

---

templates/scripts/golangci.yml.tpl

`timeCmpSimplify` recommends that you replace `!time.Before()` with `time.After()`, but these are not actually compatible (strictly-less being replaced with strictly-greater). Same with `!time.After()` and `time.Before()`.

fix(linters): Disable the timeCmpSimplify linter.

---

templates/.snapshots/TestRenderDependabot-.github-dependabot.yml.tpl-.github-dependabot.yml.snapshot
templates/_helpers.tpl
templates/api/clients/node/package.hjson.tpl

We stopped using this elsewhere, but it was left behind in the node client.
[XX-XX]

fix: remove @outreach/prettier-config from node client

---

templates/api/kubernetes/version.go.tpl

- Adds the `-e` option to the bash invocation in the `go:generate` comment for Kubernetes controller code-gen
- Without the `-e`, bash will silently eat any errors from `controller-gen`
[QSS-1430]
Before change:
```
❯ make gogenerate
:: Running gogenerate
github.com/getoutreach/database-provisioning-operator/api/k8s/database/v1:-: name requested for invalid type: interface{}
github.com/getoutreach/database-provisioning-operator/api/k8s/database/v1:-: invalid map value type: interface{}
Error: not all generators ran successfully
run `controller-gen object paths=./api/k8s/database/v1 -w` to see all available markers, or `controller-gen object paths=./api/k8s/database/v1 -h` for usage
❯ echo $?
0
``` 
after change:
```
❯ make gogenerate
:: Running gogenerate …
```

fix(k8s): error if controller-gen fails

---

manifest.yaml
templates/_helpers.tpl

This PR moves terraform version mgmt to stencil-golang as per discussion here: https://outreach-hq.slack.com/archives/CN9MU7GLW/p1668191998007089. Another PR pending on stencil-outreach to hook into the golang's version of the terraform instead of redeclaring it.
This PR also bumps the default from 0.13.5  to 0.14.11. If somebody has an issue with it, please do not revert the PR and instead force the version backwards in your service.yaml using the arguments -> versions -> terraform field.
Reason for a bump: clerk and smartstore has provisioned dashboards that rely on 0.14 experiments and functionality.
[CDT-104]
Also tested on https://github.com/getoutreach/pgtestservice/pull/38 - clerk and smartstore terraforms were applied successfully using terraform 0.14.11.
[CDT-104]: …

fix: move terraform version to be owned by golang

---

docs/module-hooks.md
templates/devspace.yaml.tpl

Adds a module hook to allow other modules to register devspace app profiles.  See video for scenario.
Video: https://share.getcloudapp.com/nOu1mPJr
[XX-XX]

feat: add module hook for devspace app profiles

---

manifest.yaml
templates/api/rpc_helpers.go.tpl

To be able to use properly protoAPI we need to be able to switch off protoc generation from golang module.
[ORES-1803]
[ORES-1803]: https://outreach-io.atlassian.net/browse/ORES-1803?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: [ORES-1803] Switch to be able to turn of grpc proto generation

---

templates/monitoring/datadog.tf.tpl

Setting the default value to zero will present missing data as `0`, which is how we want to interpret it so that our monitors and SLOs don't fire when data is missing.
[DT-3381]
[DT-3381]: https://outreach-io.atlassian.net/browse/DT-3381?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: missing data should not set off monitors

---

docs/module-hooks.md
templates/devspace.yaml.tpl

Allows for adding extra forwarded ports durning `devenv apps run`.  Needed to add port graphql is running on.
[XX-XX]

feat: add module hook to allow for extra forwarded ports in devspace

---

docs/module-hooks.md
templates/Makefile.tpl

Adds a module hook to allow other modules to add Make commands to the root Makefile.
Allows `stencil-graphql` to add a command for running the rover-cli for dev work.
[XX-XX]

feat: add module hook to add make commands

---

templates/devspace.yaml.tpl

Have devspace default to the container named after the service/app to handle multiple container pods. This should handle most use cases.
[DT-3136]
[DT-3136]: https://outreach-io.atlassian.net/browse/DT-3136?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix:  devspace handle multiple containers

---

templates/api/clients/node/src/client-helpers.ts.tpl

This change allows developers to pass in [ChannelOptions](https://github.com/grpc/grpc-node/blob/master/packages/grpc-js/src/channel-options.ts#L23) during node client initialization.
[XX-XX]

feat: added ChannelOptions param to client-helpers ClientOptions

---

templates/.snapshots/TestRenderDeploymentJsonnet-deployments-appname-app.jsonnet.tpl-deployments-testing-testing.jsonnet.snapshot
templates/.snapshots/TestRenderDeploymentOverride-deployments-appname-app.override.jsonnet.tpl-deployments-testing-testing.override.jsonnet.snapshot
templates/deployments/appname/app.jsonnet.tpl
templates/deployments/appname/app.override.jsonnet.tpl

When using a horizontalPodAutoscaler (HPA) it's recommended to have that specify the replicas and not the deployment. Currently this isn't possible. This wraps the final jsonnet render in a `std.prune` to cull any null fields, and adds an example for how to remove the replicas field from a deployment when rolling out an HPA.
Docs: https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#migrating-deployments-and-statefulsets-to-horizontal-autoscaling
[DT-3458]
[DT-3458]: https://outreach-io.atlassian.net/browse/DT-3458?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add ability to remove deployment replicas when using hpa

---

templates/cmd/main.go.tpl
templates/internal/appName/config.go.tpl
templates/internal/appName/http/httpservice.go.tpl
templates/internal/appName/rpc/rpc.go.tpl
templates/internal/appName/rpc/server.go.tpl

Also had to add a new imports module hook to handle stuff from:
https://github.com/getoutreach/stencil-outreach/pull/113/files

fix(DT-3543): Cleaning up out-of-the-box imports

---

templates/.vscode/launch.json.tpl

After we added the build flag `trimpath`, instead of absolute file system paths, the recorded file names will begin either a module path@version (when using modules), or a plain import path (when using the standard library, or GOPATH).
We need to update `substitutePath` in vscode debug settings so that the debugger can find the proper code path.
[XX-XX]

fix: correct vscode debugger path mapping

---

manifest.yaml
templates/.snapshots/TestDatadogTf_Override-monitoring-datadog.tf.tpl-monitoring-datadog.tf.snapshot
templates/.snapshots/TestRenderDeploymentJsonnet_Canary-deployments-appname-app.jsonnet.tpl-deployments-testing-testing.jsonnet.snapshot
templates/.snapshots/TestRenderDeploymentJsonnet_Canary_emptyServiceActivities-deployments-appname-app.jsonnet.tpl-deployments-testing-testing.jsonnet.snapshot
templates/deployments/appname/app.jsonnet.tpl
templates/main_test.go
templates/monitoring/datadog.tf.tpl

- add override for pod-restart threshold for datadog terraform
- add pod-restart metric for Canary Deployment
[sample data](https://app.datadoghq.com/metric/explorer?start=1677536318490&end=1677539918490&paused=false#N4Ig7glgJg5gpgFxALlAGwIYE8D2BXJVEADxQEYAaELcqyKBAC1pEbghkcLIF8qo4AMwgA7CAgg4RKUAiwAHOChASAtnADOcAE4RNIKtrgBHPJoQaUAbVBGN8qVoD6gnNtUZCKiOq279VKY6epbINiAiGOrKQdpYZAYgUJ4YThr42gDGSsgg6gi6mZaBZnHKGniqyADWeABGOiKImmkInnAAdJlSbaI6HXZt2hbAtQ1O3SK9TdpOkerIAvJoOFgI5n4AbhDZFGNwc1Ga8hjZi3DLq+saFjrb2QC0DzcYMKIwAEx1PAAEdVg-YDaHBoOA8EA8AC6VFc7jwmFC4VhqnhGGUAkEGHhCCcAC8dDgABSxeIASgh0JANywoJkIBOoIQ63ROBgEwRGh2iTQfScckU5RB0G5vPoTGUIjcHjQEP4EHsmCwfIUORAPKaFJ4fCpy3EAGEpMIYCgRPC0DwgA)
https://outreach-io.atlassian.net/browse/DT-3531

feat: add pod-restart metrics for canary deployment

---

templates/deployments/appname/mixins/kubernetes.jsonnet.tpl

Fixing broken jsonnet-libs call after https://github.com/getoutreach/stencil-golang/commit/e9825c36865ddd7c75eba083e63bc34a2c58a91a

fix: CRDv1 incorrect syntax

---

templates/.snapshots/TestBasicGoMod-go.mod.tpl-go.mod.snapshot
templates/.snapshots/TestGoModStanzaVersion-go.mod.tpl-go.mod.snapshot
templates/.snapshots/TestMergeGoMod-go.mod.tpl-go.mod.snapshot
templates/_helpers.tpl

This PR bumps `gobox` to `v1.65.1` to fix a panic in the new `trace.Error` function.
[XX-XX]

fix(gobox): use v1.65.1

---

manifest.yaml
templates/.goreleaser.yml.tpl
templates/.snapshots/TestBasicGoMod-go.mod.tpl-go.mod.snapshot
templates/.snapshots/TestGoModStanzaVersion-go.mod.tpl-go.mod.snapshot
templates/.snapshots/TestMergeGoMod-go.mod.tpl-go.mod.snapshot
templates/_helpers.tpl
templates/cmd/main_cli.go.tpl

This PR adds support for unmanaged CLIs, useful for when you want to use the stencil CLI distribution framework but not opt into the CLI framework (e.g., no updater, or other aspects of it).
This is done by overloading the `commands` argument to support the original:
```yaml
commands:
- a-cool-command
```
but also a new format:
```yaml
commands:
- a-cool-command:
option: true
```
To opt-out, one can now set `unmanaged`:
```yaml
commands:
- a-cool-command:
unmanaged: true
```
This unmanaged the CLI file by setting it to 'static' and generating only a minimal `main.go` placeholder. Goreleaser, semantic-release, and etc are still used to package and distribute the binary as normal.
[XX-XX]

feat: support unmanaged CLIs

---

.github/dependabot.yml
.vscode/outreach.code-snippets
.vscode/private.env
opslevel.yml
service.yaml
stencil.lock

This PR adds a dependency on `stencil-outreach` so that we're able to release w/ `opslevel`
[XX-XX]

fix(release): use stencil-outreach for opslevel

---

go.mod
go.sum
templates/.snapshots/TestBasicGoMod-go.mod.tpl-go.mod.snapshot
templates/.snapshots/TestGoModStanzaVersion-go.mod.tpl-go.mod.snapshot
templates/.snapshots/TestMergeGoMod-go.mod.tpl-go.mod.snapshot
templates/_helpers.tpl

Upgrades the version of gobox in use to enable the new `gh` CLI keyring storage added in https://github.com/getoutreach/gobox/pull/298
[DT-3656]
[DT-3656]: https://outreach-io.atlassian.net/browse/DT-3656?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: upgrade gobox for new github CLI auth format support

---

manifest.yaml
templates/.snapshots/TestRenderDeploymentDockerfile-deployments-appname-Dockerfile.tpl-deployments-testing-Dockerfile.snapshot

This PR changes the version of Go back to 1.19 (but upgrades to the latest patch) due to incompat with the golangci-lint version we're stuck on (see https://github.com/getoutreach/devbase/pull/507). It hangs, forever, for no reason and consumes all the CPU. Amazing.
[XX-XX]
Requires https://github.com/getoutreach/outreach-docker/pull/580

fix(golang): use 1.19.8 due to golangci-lint incompat

---

templates/devspace.yaml.tpl

Moves from reading from the `yaml` file to the new `gh auth token`, related to https://github.com/getoutreach/gobox/pull/298.
[DT-3656]
[DT-3656]: https://outreach-io.atlassian.net/browse/DT-3656?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(devspace): support new gh keychain backend

---

templates/devspace.yaml.tpl

This PR adjusts the `GH_TOKEN` command for `devspace` to actually... work :D. See comment on the variable for an explanation on why we're doing this hackiness.
[DT-3670]
[DT-3670]: https://outreach-io.atlassian.net/browse/DT-3670?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(devspace): proper gh auth token support

---

templates/.snapshots/TestRenderDeploymentJsonnet-deployments-appname-app.jsonnet.tpl-deployments-testing-testing.jsonnet.snapshot
templates/.snapshots/TestRenderDeploymentJsonnet_Canary-deployments-appname-app.jsonnet.tpl-deployments-testing-testing.jsonnet.snapshot
templates/.snapshots/TestRenderDeploymentJsonnet_Canary_emptyServiceActivities-deployments-appname-app.jsonnet.tpl-deployments-testing-testing.jsonnet.snapshot
templates/deployments/appname/app.jsonnet.tpl

This PR adjusts the default sample percent rate from `1%` to `0.25%` (1 in 400, this is also used @ Outreach for our Ruby codebase)
[DT-3669]
[DT-3669]: https://outreach-io.atlassian.net/browse/DT-3669?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(trace): lower non dev samplepercent to 0.25 (1 in 400)

---

templates/.snapshots/TestBasicGoMod-go.mod.tpl-go.mod.snapshot
templates/.snapshots/TestGoModStanzaVersion-go.mod.tpl-go.mod.snapshot
templates/.snapshots/TestMergeGoMod-go.mod.tpl-go.mod.snapshot
templates/.snapshots/TestRenderDependabot-.github-dependabot.yml.tpl-.github-dependabot.yml.snapshot
templates/_helpers.tpl

Updates the dependencies for Go projects, for the following reasons:
* `httpx` - Fixes the HTTP server to be able to gracefully shutdown
* `grpcx` - Add the ability to disable logs and/or traces for specific endpoints
* `gobox` - Adds ability to silence logs emitted by the `trace.<*>Call` methods. Fixes a panic with the delibird logger integration.
[XX-XX]

fix(go): upgrade deps

---

templates/.snapshots/TestVSCodeLaunchConfig-.vscode-launch.json.tpl-.vscode-launch.json.snapshot
templates/main_test.go

This PR fixes the local paths to no longer reply on `-trimpath`. When https://github.com/getoutreach/devbase/pull/510 landed, we stopped using `trimpath` (unobviously) which broke the debugger path substitution. While here, I added in-line code docs to make it easier to understand what each part is doing and why it exists.
I tested this locally on `keraton`.
[DT-3746]
[DT-3746]: https://outreach-io.atlassian.net/browse/DT-3746?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(vscode): use proper debugger paths for dlv debug

---

templates/.snapshots/TestBasicGoMod-go.mod.tpl-go.mod.snapshot
templates/.snapshots/TestGoModStanzaVersion-go.mod.tpl-go.mod.snapshot
templates/.snapshots/TestMergeGoMod-go.mod.tpl-go.mod.snapshot
templates/_helpers.tpl

Hotfixes commit(s) "f356e8cd443fee79eb3754e60bcb493231acec52" into channel stable, created by `dt release hotfix`

chore: Hotfix f356e8cd443fee79eb3754e60bcb493231acec52 into channel stable

---

templates/scripts/golangci.yml.tpl

//go:generate lines cannot be shortened. This rule prevents needing to add `nolint` for the many such lines that are longer than 140 characters.
[DT-3020]
[DT-3020]: https://outreach-io.atlassian.net/browse/DT-3020?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: DT-3020 lll skips //go:generate lines

---

templates/.snapshots/TestBasicGoMod-go.mod.tpl-go.mod.snapshot
templates/.snapshots/TestGoModStanzaVersion-go.mod.tpl-go.mod.snapshot
templates/.snapshots/TestMergeGoMod-go.mod.tpl-go.mod.snapshot
templates/_helpers.tpl

This fixes an issue with delibird where stdin would not be hooked up to
the child process when stdin is not a terminal.
[DT-3742]
[DT-3742]: https://outreach-io.atlassian.net/browse/DT-3742?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(deps): update gobox

---

templates/scripts/golangci.yml.tpl

This isn't used and there's new syntax for v2 where an empty list did not work. V2 is used in golangci-lint 1.53.2
[XX-XX]

feat(golangci-lint): disable depguard

---

templates/.snapshots/TestDevspaceYaml-devspace.yaml.tpl-devspace.yaml.snapshot
templates/devspace.yaml.tpl

This specifically reverts the change to disable forwarding the DLV port by default. The functionality to override this port with an environmental variable will still exist, and that's a viable path forward to support deploying/debugging multiple applications to devspace.
[XX-XX]

fix: revert disabling dlv port forwarding by default

---

templates/.snapshots/TestDevspaceYaml-devspace.yaml.tpl-devspace.yaml.snapshot
templates/.snapshots/TestVSCodeLaunchConfig-.vscode-launch.json.tpl-.vscode-launch.json.snapshot
templates/.vscode/launch.json.tpl
templates/devspace.yaml.tpl

Add support for binary sync in devspace mode. This way we don't need to make dev machine out of devspace pod, but just synchronize binaries and have file system watcher on dev-slim package.
[QF-880]
[QF-880]: https://outreach-io.atlassian.net/browse/QF-880?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Add basic binary sync mode for devspace

---

manifest.yaml
templates/internal/appName/k8s/activity.go.tpl

Adds a leader election option to manifest.yaml so that kubernetes controllers/webhooks/operators can have this disabled.
Also fixes a bug around ctrlOptions being declared and never used, and a duplicate registration of ConfigMaps.
[DT-3816]
[DT-3816]: https://outreach-io.atlassian.net/browse/DT-3816?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: include kubernetes leaderelection option

---

templates/.vscode/settings.json.tpl

Avoids PRs which add trailing whitespace, followed by PRs which run `make fmt`.

feat(vscode): remove trailing whitespace on save

---

templates/.snapshots/TestDatadogTf-monitoring-datadog.tf.tpl-monitoring-datadog.tf.snapshot
templates/.snapshots/TestDatadogTf_Override-monitoring-datadog.tf.tpl-monitoring-datadog.tf.snapshot
templates/monitoring/datadog.tf.tpl

I don't believe in memory alerts, to begin with. They also don't work with the new automemlimit work which encourages Go to use 90% of available RAM.

fix(monitoring): remove memory alerts

---

templates/monitoring/versions.tf.tpl

This PR puts an upper bound on the datadog terraform provider version. It looks like a recent version broke something and this prevents us from using that version.
[DT-3874]
[DT-3874]: https://outreach-io.atlassian.net/browse/DT-3874?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Upper bound for datadog terraform provider

---

manifest.yaml
templates/.snapshots/TestRenderDeploymentDockerfile-deployments-appname-Dockerfile.tpl-deployments-testing-Dockerfile.snapshot
templates/.snapshots/TestVSCodeLaunchConfig-.vscode-launch.json.tpl-.vscode-launch.json.snapshot

Upgrades Go `1.19.11` to fix some vulnerabilies, most notably CVE-2023-29405[1].
[1]: https://access.redhat.com/security/cve/CVE-2023-29405

fix: upgrade go to 1.19.11 to fix vulns

---

templates/.snapshots/TestDevspaceYaml-devspace.yaml.tpl-devspace.yaml.snapshot
templates/devspace.yaml.tpl

[ORCS-3222](https://outreach-io.atlassian.net/browse/ORCS-3222)
Fixes a bug that prevented the e2e-specific sections of `devspace.yml`
from activating when they ought to.
I ran into this bug while working on the linked ticket.  Running `devenv
apps e2e` or `devenv apps e2e -t`, I'd find that the pod this created
used the regular k8s service account, not the special one set aside for
e2e tests.
----
What was the bug and how does this commit fix it?  That's a good
question with a long answer.
When I run `devenv apps e2e -t`, this is the command that gets invoked:
```
DEPLOY_TO_DEV_VERSION=latest DEVENV_BIN=/home/rlarocque/.outreach/bin/devenv DEVENV_VERSION=v1.58.0 DEVENV_DEPLOY_VERSION=latest DEVENV_DEPLOY_IMAGE_SOURCE=remote DEVENV_DEPLOY_IMAGE_REGISTRY=gcr.io/outreach-docker …
```

fix: ORCS-3222 fix devspace e2e activation

---

templates/.snapshots/TestRenderDeploymentJsonnet-deployments-appname-app.jsonnet.tpl-deployments-testing-testing.jsonnet.snapshot
templates/.snapshots/TestRenderDeploymentJsonnetWithHPA-deployments-appname-app.jsonnet.tpl-deployments-testing-testing.jsonnet.snapshot
templates/.snapshots/TestRenderDeploymentJsonnet_Canary-deployments-appname-app.jsonnet.tpl-deployments-testing-testing.jsonnet.snapshot
templates/.snapshots/TestRenderDeploymentJsonnet_Canary_emptyServiceActivities-deployments-appname-app.jsonnet.tpl-deployments-testing-testing.jsonnet.snapshot
templates/deployments/appname/app.jsonnet.tpl

Adds an annotation to each pod created by the deployment that's an md5 of the configmap so that if a configmap gets updated by the template it'll cause the pods to cycle and load the updated configmap.
[DT-3861]
[DT-3861]: https://outreach-io.atlassian.net/browse/DT-3861?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add configmap md5 annotation to deployments

---

templates/.snapshots/TestDevspaceYaml-devspace.yaml.tpl-devspace.yaml.snapshot
templates/deployments/appname/mixins/devenv.jsonnet.tpl
templates/devspace.yaml.tpl

asdf doesn't have a good way to detect missing shims, so keeping this matching installs will make things work better.
---
Without this, every new devspace pod requires a reshim run.

fix: Create PV + PVC for asdf shims.

---

.circleci/config.yml
.github/dependabot.yml
.vscode/settings.json
manifest.yaml

Now that Outreach's.. special service... has moved to Ruby 3, we can
move grpcClients to use that by default. So, here we are. Ruby 3. Wow!
Also a misc change to ignore PRs to `main` in VSCode, since those are
created during the release process and then closed.

feat(grpcClients): move to Ruby 3

---

.vscode/extensions.json

Does what it says on the tin by adding a recommended VSCode extension.

chore(vscode): syntax highlight Go templates

---

templates/cmd/main.go.tpl

In https://github.com/getoutreach/stencil-golang/pull/121/files a change was made to force exit the code while leaving main(), which was also executed when a panic was being thrown, swallowing and "hiding" it.
This change will at least print it to stderr for debugging.
Not sure whether we should instead make a formatted log entry but this is how panics used to be surfaced before.
[XX-XX]
TESTED=not tested

fix: don't swallow panics

---

monitoring/slos.tf
templates/.snapshots/TestDontIncludeRubyToolVersionsIfNotRubyGRPCCLient-testdata-tool-versions-ruby-.tool-versions.tpl-testdata-tool-versions-ruby-.tool-versions.snapshot
templates/.snapshots/TestIncludeRubyToolVersionsIfRubyGRPCCLient-testdata-tool-versions-ruby-.tool-versions.tpl-testdata-tool-versions-ruby-.tool-versions.snapshot
templates/_helpers.tpl
templates/api/clients/ruby/.tool-versions.tpl
templates/main_test.go
templates/testdata/tool-versions-ruby/.tool-versions.tpl

Fixes `ruby` availability to be available to the entire repository if
the `ruby` grpc client is enabled. This fixes an issue where devbase
would skip configuring bundle authentication if `bundle` isn't available
in the root of the repo.
I hacked in tests by making a `testdata` folder containing a template
used to determine if we successfully included ruby or not based on the
specified arguments. This doesn't output to disk, thanks to the
`file.Skip` but is still able to be handled as a snapshot for testing.
Eventually, the new stencil testing framework will support this better.
**JIRA**: [DT-3995]
[DT-3995]: https://outreach-io.atlassian.net/browse/DT-3995?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(grpcClients): add ruby to root .tool-versions if enabled

---

manifest.yaml

Updates then nodejs version used by build tooling
to be v18.17. This is NOT used for gRPC generation.

fix(node): upgrade build nodejs version

---

templates/.snapshots/TestDontIncludeRubyToolVersionsIfNotRubyGRPCCLient-testdata-tool-versions-ruby-.tool-versions.tpl-testdata-tool-versions-ruby-.tool-versions.snapshot
templates/.snapshots/TestIncludeRubyToolVersionsIfRubyGRPCCLient-testdata-tool-versions-ruby-.tool-versions.tpl-testdata-tool-versions-ruby-.tool-versions.snapshot

Follow-up to #361, fixes the CI failure.

test: update tool-versions snapshots

---

templates/internal/appName/rpc/rpc.go.tpl

Fixes indentation, whitespace, and output when there are no gRPC opts or
init functions. Otherwise the linter could yell.

fix(rpc): indent properly when no gRPC opts/init

---

templates/.snapshots/TestVSCodeLaunchConfig-.vscode-launch.json.tpl-.vscode-launch.json.snapshot
templates/.vscode/launch.json.tpl

Updates the path used for mapping from the host to a path in the
devspace pod. This was changed a few PRs ago to use the same paths as
the host (minus `$HOME` prefix) for simplicity, but this path wasn't
updated.

fix(vscode): use correct to path for GOMODCACHE

---

manifest.yaml

Node.js 16 is EOL as of 2023-09-11 (per the [Node.js Release working group](https://github.com/nodejs/Release)).

fix(grpc): upgrade Node.js version to 18

---

templates/scripts/golangci.yml.tpl

There is a formatter for generated resolvers introduced in [another PR](https://github.com/getoutreach/stencil-graphql/pull/152) that removes most of the issues linter would complaint about semi-generated GraphQL resolvers. The last problem is the line length and not combined parameters of resolver methods. Formatting would be non-trivial, so for now we can just add ignore rule in scripts/golangci.yml.
[XX-XX]

fix: allow linter on semi-generated gql resolvers

---

templates/api/clients/node/package.hjson.tpl

Updates the scope of the generated gRPC client to be `@getoutreach`
which is exclusively published to Github Packages.
[DT-4053]
[DT-4053]: https://outreach-io.atlassian.net/browse/DT-4053?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: use @getoutreach for gRPC client scope

---

templates/api/clients/node/.eslintrc.js.tpl
templates/api/clients/node/README.md.tpl
templates/api/clients/node/jest.config.js.tpl
templates/api/clients/node/scripts/copy-definitions.js.tpl
templates/api/clients/node/src/client-helpers.ts.tpl
templates/api/clients/node/tsconfig.json.tpl

There were a few `@outreach` scope changes that were missed. This
updates them to be `@getoutreach`.
[DT-4053]
[DT-4053]: https://outreach-io.atlassian.net/browse/DT-4053?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(nodeGRPCClient): missed some scope updates

---

bootstrap.lock
templates/_helpers.tpl

Upgrades `grpc-tools` to fix issues with M1 Macs and node 20 binaries.

fix(node): upgrade grpc-tools

---

templates/api/clients/node/tsconfig.json.tpl

This change prevents potential build failures by telling the typescript compiler not to include types from parent node modules, which it does by default (which is terrible default behavior that we have to compensate for, ugh).
Docs on the subject: https://www.typescriptlang.org/tsconfig#typeRoots
Relevant quote:
> By default all visible "`@types`" packages are included in your compilation. Packages in `node_modules/@types` of any enclosing folder are considered visible. For example, that means packages within `./node_modules/@types/`, `../node_modules/@types/`, `../../node_modules/@types/`, and so on.
Without this change we were seeing `yarn build` fail because `tsc` run in `api/clients/node/` wouldn't limit it's type definitions to those in `api/clients/node/node_modules`, it'd also …

fix: Prevent build failures by limiting type scope

---

manifest.yaml

The current behavior of stencil is that if you put an RC version in the version field of a dependency module, it will require the RC channel, even after a non-RC version of that module has been released. So, update the minimum version to be a non-RC version.

fix(manifest): depend on a non-RC version of devbase

---

manifest.yaml

Hotfixes commit(s) "2ded2125b072bec9dffdfae07cc17e956b5f6450" into channel stable, created by `dt release hotfix`

chore: Hotfix 2ded2125b072bec9dffdfae07cc17e956b5f6450 into channel stable

---

templates/.snapshots/TestDevspaceYaml-devspace.yaml.tpl-devspace.yaml.snapshot
templates/devspace.yaml.tpl

This is causing issues in various places, and it's unclear if anyone's actually depending on this. We're open to reverting this if the removal affects users negatively.
[DT-4124]
[DT-4124]: https://outreach-io.atlassian.net/browse/DT-4124?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(devspace): remove kubectl proxy command

---

templates/.snapshots/TestDevspaceYaml-devspace.yaml.tpl-devspace.yaml.snapshot
templates/devspace.yaml.tpl

In binary sync profile, we were overwriting the entire 'sync' section, this prevented the copy of migration directories. This change ensures that we do copy this over as well. 
[XX-XX]

fix: Makes sure binary sync profile copies migration dir

---

templates/api/clients/node/package.hjson.tpl

Linting and formatting should already have been run in the PR CI, it doesn't need to run when building for release.

fix(nodejs): do not run lint/format during client build

---

templates/.snapshots/TestGRPCServerRPC-internal-appName-rpc-rpc.go.tpl-internal-testing-rpc.go.snapshot
templates/internal/appName/rpc/rpc.go.tpl
templates/main_test.go

Avoids adding an extra empty line at the beginning of the `StartServers` function, which is a lint error.
Also fixes a weird mixed whitespace issue found when generating a snapshot of the same file. (This is normally fixed with `go fmt` so it's not an issue in practice.)
[DT-4160]
[DT-4160]: https://outreach-io.atlassian.net/browse/DT-4160?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(rpc): avoid lint error when there are no server options

---

templates/deployments/appname/resources.libsonnet.tpl

`deployment/$APP/mixins/accounts.env.jsonnet` doesn't seem to exist anymore and it's not referenced anywhere in this file.

fix(deployments): remove unused import

---

templates/.snapshots/TestRenderDeploymentDockerfile-deployments-appname-Dockerfile.tpl-deployments-testing-Dockerfile.snapshot
templates/deployments/appname/Dockerfile.tpl

The rds-combined-ca-bundle.pem has expired certificate authority keys, updating with latest global bundle.

fix: update the certficiate authority for rds

---

templates/cmd/main.go.tpl

This is to fix stencil for `eng` repo, when the appImportPath is not the expected package path. See the error details in the bug. The formatter will add the necessary import for internal package later.
[DT-4293]
[DT-4293]: https://outreach-io.atlassian.net/browse/DT-4293?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: remove the mandatory internal module import to avoid failure

---

go.mod
go.sum
manifest.yaml
templates/.snapshots/TestRenderDeploymentJsonnetWithHPA-deployments-appname-app.jsonnet.tpl-deployments-testing-testing.jsonnet.snapshot
templates/deployments/appname/app.jsonnet.tpl
templates/main_test.go

Adds the ability to opt-in for having deployments cycle to pick up changes in configmaps and secrets.
[DT-3321]
[DT-3321]: https://outreach-io.atlassian.net/browse/DT-3321?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add enableReloader annotation

---

templates/.snapshots/TestDevspaceYaml-devspace.yaml.tpl-devspace.yaml.snapshot
templates/devspace.yaml.tpl

Fix the bug when `--skip-portforwarding` applied, dlv port is still forwarded.
[DT-4305]
[DT-4305]: https://outreach-io.atlassian.net/browse/DT-4305?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: stop forwarding dlv port when skipped

---

templates/api/kubernetes/version.go.tpl

controller-gen panics on some of our repos now, specifically found this in database-credential-operator.
```
go run sigs.k8s.io/controller-tools/cmd/controller-gen@v0.7.0 object paths=./api/k8s/database/v1
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x103280e80]
```
https://github.com/kubernetes-sigs/controller-tools/issues/888

fix: upgrade controller-gen to 0.14.0 to fix panic

---

templates/_helpers.tpl

* it has to be pinned because it will end up indirectly resolving latest
which will not build

fix: pin grpc-js

---

templates/.snapshots/TestRenderDeploymentJsonnet-deployments-appname-app.jsonnet.tpl-deployments-testing-testing.jsonnet.snapshot
templates/.snapshots/TestRenderDeploymentJsonnetWithHPA-deployments-appname-app.jsonnet.tpl-deployments-testing-testing.jsonnet.snapshot
templates/.snapshots/TestRenderDeploymentJsonnet_Canary-deployments-appname-app.jsonnet.tpl-deployments-testing-testing.jsonnet.snapshot
templates/.snapshots/TestRenderDeploymentJsonnet_Canary_emptyServiceActivities-deployments-appname-app.jsonnet.tpl-deployments-testing-testing.jsonnet.snapshot
templates/.snapshots/TestUseKIAMFalse-deployments-appname-app.jsonnet.tpl-deployments-testing-testing.jsonnet.snapshot
templates/deployments/appname/app.jsonnet.tpl

Update LaunchDarkly context by introducing `appName` property in the user context. This property is already used by client-side SDK (OrCA) to identify various apps built in OrCA. In order to have a better overview of usage of flags across our codebase, we're introducing the `appName` property across all LD clients.
This is a backwards compatible change because it doesn't change how existing flags are evaluated. It's not expected to use this new property in feature flag targeting; instead, this will come in handy as a debugging/organization tool.
Recently, there were at least two occasions where this would have been useful:
1. An SDK sending invalid value of user id 
2. An SDK sending incorrect insights data
In both cases, having the `appName` would speed up the fault detection.
[XX-XX]

feat: send appName as an identifier in LD context

---

.circleci/config.yml
.releaserc.yaml
service.yaml

This PR is to apply test new release pattern in this repo to test the workflow. It pulls the orb and bash scripts change in [devbase](https://github.com/getoutreach/devbase/pull/743).
The applied branch in devbase has been rebased from stable.
[XX-XX]

fix: test release workflow

---

scripts/.tool-versions
templates/api/clients/node/src/client-helpers.spec.ts.tpl
templates/api/clients/node/src/client-helpers.ts.tpl
templates/api/clients/node/src/index.ts.tpl
templates/api/clients/ruby/lib/client.rb.tpl
templates/api/clients/ruby/lib/client/client.rb.tpl

When generating client packages for libraries, they won't have the actual client generated, but just the types around it. So don't emit the client classes or helpers.
[DT-4300]
[DT-4300]: https://outreach-io.atlassian.net/browse/DT-4300?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(grpc): don't emit gRPC clients for libraries

---

templates/api/clients/ruby/client.gemspec.tpl

* [set gem summary based on whether it's a service](https://github.com/getoutreach/stencil-golang/commit/a0cbd9feb2f21b033b0d6960a0e1f59c071cfdec)
* [sync required ruby version with ruby client version](https://github.com/getoutreach/stencil-golang/commit/25962549b8c1d3dcb778d403e68ee5b01647e72d)
[DT-4300]
[DT-4300]: https://outreach-io.atlassian.net/browse/DT-4300?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(ruby): update gemspec description/ruby version

---

templates/.snapshots/TestRenderDeploymentDockerfile-deployments-appname-Dockerfile.tpl-deployments-testing-Dockerfile.snapshot
templates/deployments/appname/Dockerfile.tpl

In Alpine Linux, `curl` isn't installed by default, but `busybox` is. `busybox` contains a `wget` applet which has the equivalent functionality for what we need here. When the image layer isn't cached, it seems to go from 1.1s to 0.2s.

fix(docker): avoid installing curl for the RDS certificates

---

.circleci/config.yml

The scheduled rc release will be triggered automatically on every Tuesday noon, to avoid rc get into stable without testing.
To manually trigger the pipeline on CircleCI UI:
After the workflow is verified, the ci config should be added to the `stencil-circleci` template.
[DT-4239]
[DT-4239]: https://outreach-io.atlassian.net/browse/DT-4239?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ci: add ci configuration allow manual and automatic rc release

---

.github/CODEOWNERS
templates/main_test.go
templates/ruby_test.go

DT doesn't have enough context to adequately maintain support for the Ruby gRPC client templates, so we're handing off ownership to FND: PC as they currently "own" Flagship (the only consumer of the Ruby clients).
CC: @george-e-shaw-iv (per what we discussed in Slack)

chore: change ownership of Ruby gRPC client to FND: PC

---

.tool-versions
manifest.yaml
templates/.snapshots/TestIncludeRubyToolVersionsIfRubyGRPCClient-testdata-tool-versions-ruby-.tool-versions.tpl-testdata-tool-versions-ruby-.tool-versions.snapshot
templates/.snapshots/TestIncludeRubyToolVersionsIfRubyGRPCClientLibrary-testdata-tool-versions-ruby-.tool-versions.tpl-testdata-tool-versions-ruby-.tool-versions.snapshot

This is the companion PR to https://github.com/getoutreach/stencil-base/pull/159
[DT-4322]
[DT-4322]: https://outreach-io.atlassian.net/browse/DT-4322?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: upgrade build tools Node.js version to 20 LTS

---

.releaserc.yaml
scripts/devbase.sh
service.yaml
stencil.lock

This fixes CI now that https://github.com/getoutreach/devbase/pull/743 is merged.

chore: restencil to use unstable devbase instead of a nonexistent branch

---

templates/.snapshots/TestRenderDependabot-.github-dependabot.yml.tpl-.github-dependabot.yml.snapshot
templates/_helpers.tpl

As far as I can tell, `wait-on` has never been used in the entire history of the Node.js gRPC client :rage4:
[DT-4345]
[DT-4345]: https://outreach-io.atlassian.net/browse/DT-4345?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(nodejs): remove unused wait-on devDependency

---

templates/Makefile.tpl

This should fix the conflict between re-running `stencil` and editing `Makefile` in an editor that supports EditorConfig.

fix: remove trailing whitespace from Makefile

---

templates/.snapshots/TestRenderDependabot-.github-dependabot.yml.tpl-.github-dependabot.yml.snapshot
templates/_helpers.tpl

As far as I can tell, `@grpc/proto-loader` is not used in the Node.js gRPC client by default.
Also sync the version of `@grpc/grpc-js` version with the same version used in `@getoutreach/grpc-client` to get ahead of security vulnerability tickets.
[DT-4422]
[DT-4422]: https://outreach-io.atlassian.net/browse/DT-4422?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(nodejs): remove unused `@grpc/proto-loader` & sync `@grpc/grpc-js` version

---

templates/.snapshots/TestBasicGoMod-go.mod.tpl-go.mod.snapshot
templates/.snapshots/TestGoModStanzaVersion-go.mod.tpl-go.mod.snapshot
templates/go.mod.tpl

This should ensure that the Go version specified by the manifest is the same version as the toolchain used.

fix(gomod): add toolchain directive

---

templates/_helpers.tpl

Sync the version of `@grpc/grpc-js` in the Node.js gRPC client with the version depended on by `@getoutreach/grpc-client`.
[DT-4427]
[DT-4427]: https://outreach-io.atlassian.net/browse/DT-4427?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(nodejs): upgrade `@getoutreach/grpc-client` to ^2.4.0

---

templates/api/clients/node/tsconfig.json.tpl

This should simplify the generated JS that's output. ES2022 is compatible with Node.js 20, see https://github.com/microsoft/TypeScript/wiki/Node-Target-Mapping for details. (Not using ES2023 because I don't want to upgrade TypeScript at the same time...)
This should also avoid some weird compatibility issues with `@types/node` and also removes an unnecessary `dom` include since there's no frontend code used here.

fix(nodejs): update TypeScript target/lib to ES2022

---

templates/api/clients/node/package.hjson.tpl

Using `--check` instead of `--list-different` should make it clearer to folks who don't use `prettier` by default what the problem is and how to solve it.
[DT-4452]
See also: https://github.com/getoutreach/devbase/pull/806
[DT-4452]: https://outreach-io.atlassian.net/browse/DT-4452?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(nodejs): better messaging when prettier fails

---

manifest.yaml

This is needed in particular for the gRPC client, because at least one of the transitive dependencies will no longer install under Node.js 20.8.0.
I also upgraded the Node.js version for `semantic-release` because why not, might as well have fewer Node.js versions hanging around.
[DT-4478]
[DT-4478]: https://outreach-io.atlassian.net/browse/DT-4478?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: update default Node.js versions to 20.16.0

---

internal/plugin/merge.go
internal/plugin/merge_test.go
templates/.snapshots/TestMergeGoMod-go.mod.tpl-go.mod.snapshot

Fixes the issue where `toolchain` wasn't updated when the Go version changed, because there's custom (plugin) code to merge the existing `go.mod` with the Stencil-generated one.
[DT-4486]
[DT-4486]: https://outreach-io.atlassian.net/browse/DT-4486?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(gomod): always merge in toolchain changes

---

templates/api/clients/ruby/client.gemspec.tpl

Small tweak to align with a [rule](https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/ExpandPathArguments) enforced by the VSCode RuboCop extension.
[XX-XX]

fix(ruby_client): align one file with the RuboCop rules

---

templates/api/clients/ruby/client.gemspec.tpl

When `file.Block` is empty, the spaces are left there. IDEs +`make fmt` are then trying to delete those spaces which creates a change differing from the stencil template. This small fix corrects that.
[XX-XX]

chore: fix ruby client.gemspec spaces

---

manifest.yaml
templates/.snapshots/TestBasicGoMod-go.mod.tpl-go.mod.snapshot
templates/.snapshots/TestMergeGoMod-go.mod.tpl-go.mod.snapshot

Recent Dependabot PRs have been failing with the following diff reporting from `go mod tidy`:
```diff
-go 1.22
+go 1.22.0
```
This adjusts the default so that running `stencil` and merging Dependabot PRs doesn't cause the `go` directive to constantly change.

fix: go.stanza prefers a full version

---

docs/module-hooks.md
templates/.snapshots/TestDevspaceYaml-devspace.yaml.tpl-devspace.yaml.snapshot
templates/devspace.yaml.tpl

Reverts #551 and replaces it with a module hook. The needs of private Stencil modules should not leak into public Stencil modules.
[DT-4541]
[DT-4541]: https://outreach-io.atlassian.net/browse/DT-4541?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(devspace): add module hook for binary sync patches

---

manifest.yaml
templates/.snapshots/TestBasicGoMod-go.mod.tpl-go.mod.snapshot
templates/.snapshots/TestMergeGoMod-go.mod.tpl-go.mod.snapshot

This fixes Dependabot PRs to be automatically mergeable.
[DT-4533]
[DT-4533]: https://outreach-io.atlassian.net/browse/DT-4533?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(go): sync default Go stanza with minor default Go version

---

scripts/golangci.yml
templates/.snapshots/TestRenderGolangcilintYaml-scripts-golangci.yml.tpl-scripts-golangci.yml.snapshot
templates/scripts/golangci.yml.tpl

Resolves the following warning:
> The configuration option `linters.govet.check-shadowing` is deprecated. Please enable `shadow` instead, if you are not using `enable-all`.
We are not using `enable-all`.

fix(golangci-lint): resolve govet shadow config warning

---

templates/api/clients/ruby/Gemfile.lock.tpl

Upstream uses a newer version of Bundler, which causes conflicts in CI.

fix(ruby): sync bundler version with upstream

---

templates/_helpers.tpl

fix(deps): update orgservice to 1.148.6 to update k8s dependency

---

templates/.snapshots/TestGRPCServerRPC-internal-appName-rpc-rpc.go.tpl-internal-testing-rpc.go.snapshot
templates/.snapshots/TestRenderAPIGoSuccess-api-api.go.tpl-api-testing.go.snapshot
templates/.snapshots/TestRenderDeploymentConfig-deployments-appname-app.config.jsonnet.tpl-deployments-testing-testing.config.jsonnet.snapshot
templates/.snapshots/TestRenderDeploymentJsonnet-deployments-appname-app.jsonnet.tpl-deployments-testing-testing.jsonnet.snapshot
templates/.snapshots/TestRenderDeploymentJsonnetWithHPA-deployments-appname-app.jsonnet.tpl-deployments-testing-testing.jsonnet.snapshot
templates/.snapshots/TestRenderDeploymentJsonnet_Canary-deployments-appname-app.jsonnet.tpl-deployments-testing-testing.jsonnet.snapshot
templates/.snapshots/TestRenderDeploymentJsonnet_Canary_emptyServiceActivities-deployments-appname-app.jsonnet.tpl-deployments-testing-testing.jsonnet.snapshot
templates/.snapshots/TestRenderDeploymentOverride-deployments-appname-app.override.jsonnet.tpl-deployments-testing-testing.override.jsonnet.snapshot
templates/.snapshots/TestUseKIAMFalse-deployments-appname-app.jsonnet.tpl-deployments-testing-testing.jsonnet.snapshot

New year, so snapshots need to be updated.

test: update copyright in snapshots to 2025

---

templates/.snapshots/TestGRPCServerRPC-internal-appName-rpc-rpc.go.tpl-internal-testing-rpc.go.snapshot
templates/.snapshots/TestRenderAPIGoSuccess-api-api.go.tpl-api-testing.go.snapshot
templates/.snapshots/TestRenderDeploymentConfig-deployments-appname-app.config.jsonnet.tpl-deployments-testing-testing.config.jsonnet.snapshot
templates/.snapshots/TestRenderDeploymentJsonnet-deployments-appname-app.jsonnet.tpl-deployments-testing-testing.jsonnet.snapshot
templates/.snapshots/TestRenderDeploymentJsonnetWithHPA-deployments-appname-app.jsonnet.tpl-deployments-testing-testing.jsonnet.snapshot
templates/.snapshots/TestRenderDeploymentJsonnet_Canary-deployments-appname-app.jsonnet.tpl-deployments-testing-testing.jsonnet.snapshot
templates/.snapshots/TestRenderDeploymentJsonnet_Canary_emptyServiceActivities-deployments-appname-app.jsonnet.tpl-deployments-testing-testing.jsonnet.snapshot
templates/.snapshots/TestRenderDeploymentOverride-deployments-appname-app.override.jsonnet.tpl-deployments-testing-testing.override.jsonnet.snapshot
templates/.snapshots/TestUseKIAMFalse-deployments-appname-app.jsonnet.tpl-deployments-testing-testing.jsonnet.snapshot
templates/.vscode/settings.json.tpl

From the comment I put in the settings file:
> This is disabled because it causes version mismatches between the tools used/installed by `asdf` / `stencil` templates, and the ones updated by VSCode. In particular, this is a problem with newer versions of `golangci-lint` incompatible with older versions of Go.
[DT-4570]
Requires #565 to be merged first
[DT-4570]: https://outreach-io.atlassian.net/browse/DT-4570?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(vscode): disable autoupdating Go tools to avoid mismatches

---

templates/.snapshots/TestBasicGoMod-go.mod.tpl-go.mod.snapshot
templates/.snapshots/TestGoModStanzaVersion-go.mod.tpl-go.mod.snapshot
templates/.snapshots/TestMergeGoMod-go.mod.tpl-go.mod.snapshot
templates/_helpers.tpl

See https://github.com/getoutreach/gobox/pull/608

fix: upgrade gobox to 1.102.1

---

.editorconfig
templates/_helpers.tpl
templates/api/kubernetes/version.go.tpl
templates/internal/appName/k8s/activity.go.tpl

Update the generated code when the `kubernetes.groups` in `service.yaml` is configured, when using newer, non-vulnerable versions of Kubernetes libraries.
[DT-4549]
[DT-4549]: https://outreach-io.atlassian.net/browse/DT-4549?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(helpers): update kubernetes.groups dependencies to non-vulnerable versions

---

templates/.snapshots/TestRenderDependabot-.github-dependabot.yml.tpl-.github-dependabot.yml.snapshot
templates/_helpers.tpl
templates/api/clients/node/package.hjson.tpl

We only officially support macOS and Linux, both of which have working `rm -rf` commands. If we supported Windows (outside of WSL, and even only marginally at that currently), then we'd have to consider doing something like `node -e 'fs.rmSync("dist", {force: true, recursive: true})'`

fix(nodejs): remove rimraf as a devDependency

---

manifest.yaml
templates/.snapshots/TestIncludeRubyToolVersionsIfRubyGRPCClient-testdata-tool-versions-ruby-.tool-versions.tpl-testdata-tool-versions-ruby-.tool-versions.snapshot
templates/.snapshots/TestIncludeRubyToolVersionsIfRubyGRPCClientLibrary-testdata-tool-versions-ruby-.tool-versions.tpl-testdata-tool-versions-ruby-.tool-versions.snapshot

Does what it says on the tin.
[DT-4746]
[DT-4746]: https://outreach-io.atlassian.net/browse/DT-4746?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: update gRPC client Ruby version to 3.1.5

---

manifest.yaml
templates/.snapshots/TestBasicGoMod-go.mod.tpl-go.mod.snapshot
templates/.snapshots/TestGoModStanzaVersion-go.mod.tpl-go.mod.snapshot
templates/.snapshots/TestMergeGoMod-go.mod.tpl-go.mod.snapshot
templates/.snapshots/TestUrfaveCLIV2-cmd-main_cli.go.tpl-cmd-cmd1-cmd1.go.snapshot
templates/.snapshots/TestUrfaveCLIV3-cmd-main_cli.go.tpl-cmd-cmd1-cmd1.go.snapshot
templates/_helpers.tpl
templates/cmd/main_cli.go.tpl
templates/main_test.go

Adds `versions.urfave-cli` to the service manifest to allow services to use `urfave/cli/v3` instead of `v2`. Defaults to `v2` for backwards compatibility.
[DT-4762]
[DT-4762]: https://outreach-io.atlassian.net/browse/DT-4762?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add conditional support for `urfave/cli/v3`

---

templates/.snapshots/TestBasicGoMod-go.mod.tpl-go.mod.snapshot
templates/.snapshots/TestGoModStanzaVersion-go.mod.tpl-go.mod.snapshot
templates/.snapshots/TestMergeGoMod-go.mod.tpl-go.mod.snapshot
templates/_helpers.tpl

Another bump for CLIs.
[DT-4767]
[DT-4767]: https://outreach-io.atlassian.net/browse/DT-4767?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(gobox): bump required version to 1.107.1

---

CONTRIBUTING.md
templates/.snapshots/TestDevspaceYaml-devspace.yaml.tpl-devspace.yaml.snapshot
templates/devspace.yaml.tpl

`--skip-portforwarding` option in devenv apps lets dlv port to be forwarded, this PR disables port forwarding altogether if the flag is used.
[DT-4805]
[DT-4805]: https://outreach-io.atlassian.net/browse/DT-4805?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(devspace): skipPortForwarding does not prevent default ports to be forwarded

---

templates/.github/dependabot.yml.tpl
templates/.snapshots/TestRenderDependabot-.github-dependabot.yml.tpl-.github-dependabot.yml.snapshot

The use case for this is when we want to manually upgrade a block of Go dependencies.

fix(dependabot): add Go ignore block

---

templates/.snapshots/TestRenderDependabot-.github-dependabot.yml.tpl-.github-dependabot.yml.snapshot
templates/_helpers.tpl

A newer version of `@types/node` does not work with the pinned version of TypeScript that we use for the Node.js gRPC client.
[DT-4835]
[DT-4835]: https://outreach-io.atlassian.net/browse/DT-4835?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(node): pin `@types/node` version

---

templates/.snapshots/TestDevspaceYaml-devspace.yaml.tpl-devspace.yaml.snapshot
templates/devspace.yaml.tpl

This should make devspace initialization a little faster since it doesn't have to compile `Magefile.go`.
[DT-4631]
[DT-4631]: https://outreach-io.atlassian.net/browse/DT-4631?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(devspace): use mise version task instead of make target
